; Generated by tools/port_reference.py; audit against reference labels.
Case 257 ; FORTRAN 791 label 79
  *s\phase = 258
  Emit(*db, *out, 6, 5)
Case 258 ; FORTRAN 792
  *s\phase = 259
  *s\k = 52
Case 259 ; FORTRAN 793
  *s\phase = 260
  *s\phase = 250 : Continue
Case 260 ; FORTRAN 798 label 2000
  *s\phase = 261
  If Bool(*s\loc = 0)
    *s\phase = 498 : Continue
  EndIf
Case 261 ; FORTRAN 799
  *s\phase = 262
  *s\kk = *db\stext[*s\loc]
Case 262 ; FORTRAN 800
  *s\phase = 263
  If Bool(Bool((*s\abb[*s\loc] % *s\abbnum) = 0) Or Bool(*s\kk = 0))
    *s\kk = *db\ltext[*s\loc]
  EndIf
Case 263 ; FORTRAN 801
  *s\phase = 264
  If Bool(Forced(*db, *s, *s\loc) Or Bool(Not Dark(*db, *s, 0)))
    *s\phase = 266 : Continue
  EndIf
Case 264 ; FORTRAN 802
  *s\phase = 265
  If Bool(*s\wzdark And Bool(RandomRange(*s, 100) < 35))
    *s\phase = 496 : Continue
  EndIf
Case 265 ; FORTRAN 803
  *s\phase = 266
  *s\kk = *db\rtext[16]
Case 266 ; FORTRAN 804 label 2001
  *s\phase = 267
  If Toting(*db, *s, *s\bear)
    Emit(*db, *out, 6, 141)
  EndIf
Case 267 ; FORTRAN 805
  *s\phase = 268
  Speak(*db, *out, *s\kk)
Case 268 ; FORTRAN 806
  *s\phase = 269
  *s\k = 1
Case 269 ; FORTRAN 807
  *s\phase = 270
  If Forced(*db, *s, *s\loc)
    *s\phase = 388 : Continue
  EndIf
Case 270 ; FORTRAN 808
  *s\phase = 271
  If Bool(Bool(Bool(*s\loc = 33) And Bool(RandomRange(*s, 100) < 25)) And Bool(Not *s\closng))
    Emit(*db, *out, 6, 8)
  EndIf
Case 271 ; FORTRAN 816
  *s\phase = 272
  If Dark(*db, *s, 0)
    *s\phase = 292 : Continue
  EndIf
Case 272 ; FORTRAN 817
  *s\phase = 273
  *s\abb[*s\loc] = (*s\abb[*s\loc] + 1)
Case 273 ; FORTRAN 818
  *s\phase = 274
  *s\i = *s\atloc[*s\loc]
Case 274 ; FORTRAN 819 label 2004
  *s\phase = 275
  If Bool(*s\i = 0)
    *s\phase = 292 : Continue
  EndIf
Case 275 ; FORTRAN 820
  *s\phase = 276
  *s\obj = *s\i
Case 276 ; FORTRAN 821
  *s\phase = 277
  If Bool(*s\obj > 100)
    *s\obj = (*s\obj - 100)
  EndIf
Case 277 ; FORTRAN 822
  *s\phase = 278
  If Bool(Bool(*s\obj = *s\steps) And Toting(*db, *s, *s\nugget))
    *s\phase = 287 : Continue
  EndIf
Case 278 ; FORTRAN 823
  *s\phase = 279
  If Bool(*s\prop[*s\obj] >= 0)
    *s\phase = 284 : Continue
  EndIf
Case 279 ; FORTRAN 824
  *s\phase = 280
  If *s\closed
    *s\phase = 287 : Continue
  EndIf
Case 280 ; FORTRAN 825
  *s\phase = 281
  *s\prop[*s\obj] = 0
Case 281 ; FORTRAN 826
  *s\phase = 282
  If Bool(Bool(*s\obj = *s\rug) Or Bool(*s\obj = *s\chain))
    *s\prop[*s\obj] = 1
  EndIf
Case 282 ; FORTRAN 827
  *s\phase = 283
  *s\tally = (*s\tally - 1)
Case 283 ; FORTRAN 829
  *s\phase = 284
  If Bool(Bool(*s\tally = *s\tally2) And Bool(*s\tally <> 0))
    *s\limit = IMin(35, *s\limit)
  EndIf
Case 284 ; FORTRAN 830 label 2006
  *s\phase = 285
  *s\kk = *s\prop[*s\obj]
Case 285 ; FORTRAN 831
  *s\phase = 286
  If Bool(Bool(*s\obj = *s\steps) And Bool(*s\loc = *s\fixed[*s\steps]))
    *s\kk = 1
  EndIf
Case 286 ; FORTRAN 832
  *s\phase = 287
  Emit(*db, *out, 5, *s\obj, *s\kk)
Case 287 ; FORTRAN 833 label 2008
  *s\phase = 288
  *s\i = *s\link[*s\i]
Case 288 ; FORTRAN 834
  *s\phase = 289
  *s\phase = 274 : Continue
Case 289 ; FORTRAN 836 label 2009
  *s\phase = 290
  *s\k = 54
Case 290 ; FORTRAN 837 label 2010
  *s\phase = 291
  *s\spk = *s\k
Case 291 ; FORTRAN 838 label 2011
  *s\phase = 292
  Emit(*db, *out, 6, *s\spk)
Case 292 ; FORTRAN 840 label 2012
  *s\phase = 293
  *s\verb = 0
Case 293 ; FORTRAN 841
  *s\phase = 294
  *s\obj = 0
Case 294 ; FORTRAN 847 label 2600
  *s\phase = 295
  *s\hint = 4
Case 295 ; FORTRAN 848
  *s\phase = 296
  If *s\hinted[*s\hint]
    *s\phase = 300 : Continue
  EndIf
Case 296 ; FORTRAN 849
  *s\phase = 297
  *s\idondx = *s\hint
Case 297 ; FORTRAN 850
  *s\phase = 298
  If Bool(Not Bitset(*db, *s, *s\loc, *s\idondx))
    *s\hintlc[*s\hint] = (-1)
  EndIf
Case 298 ; FORTRAN 851
  *s\phase = 299
  *s\hintlc[*s\hint] = (*s\hintlc[*s\hint] + 1)
Case 299 ; FORTRAN 852
  *s\phase = 300
  If Bool(*s\hintlc[*s\hint] >= *db\hints[*s\hint*5+1])
    *s\phase = 954 : Continue
  EndIf
Case 300 ; FORTRAN 853 label 2602
  *s\phase = 301
  *s\hint + 1
  If *s\hint <= *db\hntmax : *s\phase = 295 : EndIf
Case 301 ; FORTRAN 861
  *s\phase = 302
  If Bool(Not *s\closed)
    *s\phase = 306 : Continue
  EndIf
Case 302 ; FORTRAN 862
  *s\phase = 303
  If Bool(Bool(*s\prop[*s\oyster] < 0) And Toting(*db, *s, *s\oyster))
    Emit(*db, *out, 5, *s\oyster, 1)
  EndIf
Case 303 ; FORTRAN 864
  *s\phase = 304
  *s\i = 1
Case 304 ; FORTRAN 865
  *s\phase = 305
  *s\idondx = *s\i
Case 305 ; FORTRAN 866 label 2604
  *s\phase = 306
  If Bool(Toting(*db, *s, *s\idondx) And Bool(*s\prop[*s\idondx] < 0))
    *s\prop[*s\idondx] = ((-1) - *s\prop[*s\idondx])
  EndIf
  *s\i + 1
  If *s\i <= 100 : *s\phase = 304 : EndIf
Case 306 ; FORTRAN 868 label 2605
  *s\phase = 307
  *s\wzdark = Dark(*db, *s, 0)
Case 307 ; FORTRAN 869
  *s\phase = 308
  If Bool(Bool(*s\knfloc > 0) And Bool(*s\knfloc <> *s\loc))
    *s\knfloc = 0
  EndIf
Case 308 ; FORTRAN 870
  *s\phase = 309
  *s\i = RandomRange(*s, 1)
Case 309 ; FORTRAN 871
  *s\phase = 310
  *s\awaiting = 1 : *out\inputMode = #Command : ProcedureReturn
Case 310 ; FORTRAN 876 label 2608
  *s\phase = 311
  *s\foobar = IMin(0, (-*s\foobar))
Case 311 ; FORTRAN 877
  *s\phase = 312
  If Bool(Bool(Bool(*s\turns = 0) And Bool(*s\wd1 = ~"MAGIC")) And Bool(*s\wd2 = ~"MODE"))
  EndIf
Case 312 ; FORTRAN 878
  *s\phase = 313
  *s\turns = (*s\turns + 1)
Case 313 ; FORTRAN 879
  *s\phase = 314
  If Bool(*s\demo And Bool(*s\turns >= *s\short))
    *s\phase = 1036 : Continue
  EndIf
Case 314 ; FORTRAN 880
  *s\phase = 315
  If Bool(Bool(*s\verb = *s\say) And Bool(*s\wd2 <> ""))
    *s\verb = 0
  EndIf
Case 315 ; FORTRAN 881
  *s\phase = 316
  If Bool(*s\verb = *s\say)
    *s\phase = 356 : Continue
  EndIf
Case 316 ; FORTRAN 882
  *s\phase = 317
  If Bool(Bool(Bool(*s\tally = 0) And Bool(*s\loc >= 15)) And Bool(*s\loc <> 33))
    *s\clock1 = (*s\clock1 - 1)
  EndIf
Case 317 ; FORTRAN 883
  *s\phase = 318
  If Bool(*s\clock1 = 0)
    *s\phase = 974 : Continue
  EndIf
Case 318 ; FORTRAN 884
  *s\phase = 319
  If Bool(*s\clock1 < 0)
    *s\clock2 = (*s\clock2 - 1)
  EndIf
Case 319 ; FORTRAN 885
  *s\phase = 320
  If Bool(*s\clock2 = 0)
    *s\phase = 993 : Continue
  EndIf
Case 320 ; FORTRAN 886
  *s\phase = 321
  If Bool(*s\prop[*s\lamp] = 1)
    *s\limit = (*s\limit - 1)
  EndIf
Case 321 ; FORTRAN 887
  *s\phase = 322
  If Bool(Bool(Bool(Bool(*s\limit <= 30) And Here(*db, *s, *s\batter)) And Bool(*s\prop[*s\batter] = 0)) And Here(*db, *s, *s\lamp))
    *s\phase = 1016 : Continue
  EndIf
Case 322 ; FORTRAN 889
  *s\phase = 323
  If Bool(*s\limit = 0)
    *s\phase = 1029 : Continue
  EndIf
Case 323 ; FORTRAN 890
  *s\phase = 324
  If Bool(Bool(*s\limit < 0) And Bool(*s\loc <= 8))
    *s\phase = 1033 : Continue
  EndIf
Case 324 ; FORTRAN 891
  *s\phase = 325
  If Bool(*s\limit <= 30)
    *s\phase = 1022 : Continue
  EndIf
Case 325 ; FORTRAN 892 label 19999
  *s\phase = 326
  *s\k = 43
Case 326 ; FORTRAN 893
  *s\phase = 327
  If Bool(Liqloc(*db, *s, *s\loc) = *s\water)
    *s\k = 70
  EndIf
Case 327 ; FORTRAN 894
  *s\phase = 328
  If Bool(Bool(*s\wd1 = ~"ENTER") And (Bool(Bool(*s\wd2 = ~"STREA") Or Bool(*s\wd2 = ~"WATER"))))
    *s\phase = 290 : Continue
  EndIf
Case 328 ; FORTRAN 896
  *s\phase = 329
  If Bool(Bool(*s\wd1 = ~"ENTER") And Bool(*s\wd2 <> ""))
    *s\phase = 340 : Continue
  EndIf
Case 329 ; FORTRAN 897
  *s\phase = 330
  If Bool((Bool(Bool(*s\wd1 <> ~"WATER") And Bool(*s\wd1 <> ~"OIL"))) Or (Bool(Bool(*s\wd2 <> ~"PLANT") And Bool(*s\wd2 <> ~"DOOR"))))
    *s\phase = 331 : Continue
  EndIf
Case 330 ; FORTRAN 899
  *s\phase = 331
  If At(*db, *s, Vocab(*db, *s\wd2, 1))
    *s\wd2 = ~"POUR"
  EndIf
Case 331 ; FORTRAN 900 label 2610
  *s\phase = 332
  If Bool(*s\wd1 <> ~"WEST")
    *s\phase = 334 : Continue
  EndIf
Case 332 ; FORTRAN 901
  *s\phase = 333
  *s\iwest = (*s\iwest + 1)
Case 333 ; FORTRAN 902
  *s\phase = 334
  If Bool(*s\iwest = 10)
    Emit(*db, *out, 6, 17)
  EndIf
Case 334 ; FORTRAN 903 label 2630
  *s\phase = 335
  *s\i = Vocab(*db, *s\wd1, (-1))
Case 335 ; FORTRAN 904
  *s\phase = 336
  If Bool(*s\i = (-1))
    *s\phase = 344 : Continue
  EndIf
Case 336 ; FORTRAN 905
  *s\phase = 337
  *s\k = (*s\i % 1000)
Case 337 ; FORTRAN 906
  *s\phase = 338
  *s\kq = (IDiv(*s\i, 1000) + 1)
Case 338 ; FORTRAN 907
  *s\phase = 339
  Select *s\kq
    Case 1 : *s\phase = 388
    Case 2 : *s\phase = 358
    Case 3 : *s\phase = 349
    Case 4 : *s\phase = 290
  EndSelect
  Continue
Case 339 ; FORTRAN 908
  *s\phase = 340
  *out\text + "Internal reference error " + Str(22) : *out\inputMode = #Ended : *s\ended = 1 : ProcedureReturn
Case 340 ; FORTRAN 912 label 2800
  *s\phase = 341
  *s\wd1 = *s\wd2
Case 341 ; FORTRAN 913
  *s\phase = 342
  *s\wd1x = *s\wd2x
Case 342 ; FORTRAN 914
  *s\phase = 343
  *s\wd2 = ""
Case 343 ; FORTRAN 915
  *s\phase = 344
  *s\phase = 331 : Continue
Case 344 ; FORTRAN 919 label 3000
  *s\phase = 345
  *s\spk = 60
Case 345 ; FORTRAN 920
  *s\phase = 346
  If Bool(RandomRange(*s, 100) < 20)
    *s\spk = 61
  EndIf
Case 346 ; FORTRAN 921
  *s\phase = 347
  If Bool(RandomRange(*s, 100) < 20)
    *s\spk = 13
  EndIf
Case 347 ; FORTRAN 922
  *s\phase = 348
  Emit(*db, *out, 6, *s\spk)
Case 348 ; FORTRAN 923
  *s\phase = 349
  *s\phase = 294 : Continue
Case 349 ; FORTRAN 928 label 4000
  *s\phase = 350
  *s\verb = *s\k
Case 350 ; FORTRAN 929
  *s\phase = 351
  *s\spk = *db\actspk[*s\verb]
Case 351 ; FORTRAN 930
  *s\phase = 352
  If Bool(Bool(*s\wd2 <> "") And Bool(*s\verb <> *s\say))
    *s\phase = 340 : Continue
  EndIf
Case 352 ; FORTRAN 931
  *s\phase = 353
  If Bool(*s\verb = *s\say)
    *s\obj = Bool(*s\wd2 <> "")
  EndIf
Case 353 ; FORTRAN 932
  *s\phase = 354
  If Bool(*s\obj <> 0)
    *s\phase = 356 : Continue
  EndIf
Case 354 ; FORTRAN 936 label 4080
  *s\phase = 355
  Select *s\verb
    Case 1 : *s\phase = 522
    Case 2 : *s\phase = 518
    Case 3 : *s\phase = 518
    Case 4 : *s\phase = 610
    Case 5 : *s\phase = 289
    Case 6 : *s\phase = 610
    Case 7 : *s\phase = 665
    Case 8 : *s\phase = 672
    Case 9 : *s\phase = 518
    Case 10 : *s\phase = 518
    Case 11 : *s\phase = 291
    Case 12 : *s\phase = 682
    Case 13 : *s\phase = 733
    Case 14 : *s\phase = 754
    Case 15 : *s\phase = 761
    Case 16 : *s\phase = 518
    Case 17 : *s\phase = 518
    Case 18 : *s\phase = 812
    Case 19 : *s\phase = 518
    Case 20 : *s\phase = 821
    Case 21 : *s\phase = 518
    Case 22 : *s\phase = 863
    Case 23 : *s\phase = 882
    Case 24 : *s\phase = 888
    Case 25 : *s\phase = 894
    Case 26 : *s\phase = 910
    Case 27 : *s\phase = 914
    Case 28 : *s\phase = 518
    Case 29 : *s\phase = 518
    Case 30 : *s\phase = 940
    Case 31 : *s\phase = 951
  EndSelect
  Continue
Case 355 ; FORTRAN 944
  *s\phase = 356
  *out\text + "Internal reference error " + Str(23) : *out\inputMode = #Ended : *s\ended = 1 : ProcedureReturn
Case 356 ; FORTRAN 948 label 4090
  *s\phase = 357
  Select *s\verb
    Case 1 : *s\phase = 527
    Case 2 : *s\phase = 558
    Case 3 : *s\phase = 600
    Case 4 : *s\phase = 618
    Case 5 : *s\phase = 289
    Case 6 : *s\phase = 618
    Case 7 : *s\phase = 665
    Case 8 : *s\phase = 672
    Case 9 : *s\phase = 677
    Case 10 : *s\phase = 291
    Case 11 : *s\phase = 291
    Case 12 : *s\phase = 682
    Case 13 : *s\phase = 733
    Case 14 : *s\phase = 758
    Case 15 : *s\phase = 761
    Case 16 : *s\phase = 768
    Case 17 : *s\phase = 770
    Case 18 : *s\phase = 291
    Case 19 : *s\phase = 815
    Case 20 : *s\phase = 815
    Case 21 : *s\phase = 833
    Case 22 : *s\phase = 863
    Case 23 : *s\phase = 882
    Case 24 : *s\phase = 291
    Case 25 : *s\phase = 291
    Case 26 : *s\phase = 291
    Case 27 : *s\phase = 919
    Case 28 : *s\phase = 927
    Case 29 : *s\phase = 937
    Case 30 : *s\phase = 291
    Case 31 : *s\phase = 291
  EndSelect
  Continue
Case 357 ; FORTRAN 956
  *s\phase = 358
  *out\text + "Internal reference error " + Str(24) : *out\inputMode = #Ended : *s\ended = 1 : ProcedureReturn
Case 358 ; FORTRAN 964 label 5000
  *s\phase = 359
  *s\obj = *s\k
Case 359 ; FORTRAN 965
  *s\phase = 360
  If Bool(Bool(*s\fixed[*s\k] <> *s\loc) And Bool(Not Here(*db, *s, *s\k)))
    *s\phase = 365 : Continue
  EndIf
Case 360 ; FORTRAN 966 label 5010
  *s\phase = 361
  If Bool(*s\wd2 <> "")
    *s\phase = 340 : Continue
  EndIf
Case 361 ; FORTRAN 967
  *s\phase = 362
  If Bool(*s\verb <> 0)
    *s\phase = 356 : Continue
  EndIf
Case 362 ; FORTRAN 968
  *s\phase = 363
  *s\render = RTrim(*s\wd1 + *s\wd1x) + ~"?"
  *s\k = Len(*s\render)
Case 363 ; FORTRAN 969
  *s\phase = 364
  Text(*out, "What do you want to do with the " + *s\render, 5015)
Case 364 ; FORTRAN 971
  *s\phase = 365
  *s\phase = 294 : Continue
Case 365 ; FORTRAN 973 label 5100
  *s\phase = 366
  If Bool(*s\k <> *s\grate)
    *s\phase = 369 : Continue
  EndIf
Case 366 ; FORTRAN 974
  *s\phase = 367
  If Bool(Bool(Bool(*s\loc = 1) Or Bool(*s\loc = 4)) Or Bool(*s\loc = 7))
    *s\k = *s\dprssn
  EndIf
Case 367 ; FORTRAN 975
  *s\phase = 368
  If Bool(Bool(*s\loc > 9) And Bool(*s\loc < 15))
    *s\k = *s\entrnc
  EndIf
Case 368 ; FORTRAN 976
  *s\phase = 369
  If Bool(*s\k <> *s\grate)
    *s\phase = 388 : Continue
  EndIf
Case 369 ; FORTRAN 977 label 5110
  *s\phase = 370
  If Bool(*s\k <> *s\dwarf)
    *s\phase = 373 : Continue
  EndIf
Case 370 ; FORTRAN 978
  *s\phase = 371
  *s\i = 1
Case 371 ; FORTRAN 979
  *s\phase = 372
  If Bool(Bool(*s\dloc[*s\i] = *s\loc) And Bool(*s\dflag >= 2))
    *s\phase = 360 : Continue
  EndIf
Case 372 ; FORTRAN 980 label 5112
  *s\phase = 373
  *s\i + 1
  If *s\i <= 5 : *s\phase = 371 : EndIf
Case 373 ; FORTRAN 981 label 5120
  *s\phase = 374
  If Bool((Bool(Bool(Liq(*db, *s, 0) = *s\k) And Here(*db, *s, *s\bottle))) Or Bool(*s\k = Liqloc(*db, *s, *s\loc)))
    *s\phase = 360 : Continue
  EndIf
Case 374 ; FORTRAN 982
  *s\phase = 375
  If Bool(Bool(Bool(*s\obj <> *s\plant) Or Bool(Not At(*db, *s, *s\plant2))) Or Bool(*s\prop[*s\plant2] = 0))
    *s\phase = 377 : Continue
  EndIf
Case 375 ; FORTRAN 983
  *s\phase = 376
  *s\obj = *s\plant2
Case 376 ; FORTRAN 984
  *s\phase = 377
  *s\phase = 360 : Continue
Case 377 ; FORTRAN 985 label 5130
  *s\phase = 378
  If Bool(Bool(*s\obj <> *s\knife) Or Bool(*s\knfloc <> *s\loc))
    *s\phase = 381 : Continue
  EndIf
Case 378 ; FORTRAN 986
  *s\phase = 379
  *s\knfloc = (-1)
Case 379 ; FORTRAN 987
  *s\phase = 380
  *s\spk = 116
Case 380 ; FORTRAN 988
  *s\phase = 381
  *s\phase = 291 : Continue
Case 381 ; FORTRAN 989 label 5140
  *s\phase = 382
  If Bool(Bool(*s\obj <> *s\rod) Or Bool(Not Here(*db, *s, *s\rod2)))
    *s\phase = 384 : Continue
  EndIf
Case 382 ; FORTRAN 990
  *s\phase = 383
  *s\obj = *s\rod2
Case 383 ; FORTRAN 991
  *s\phase = 384
  *s\phase = 360 : Continue
Case 384 ; FORTRAN 992 label 5190
  *s\phase = 385
  If Bool((Bool(Bool(*s\verb = *s\find) Or Bool(*s\verb = *s\invent))) And Bool(*s\wd2 = ""))
    *s\phase = 360 : Continue
  EndIf
Case 385 ; FORTRAN 993
  *s\phase = 386
  *s\render = RTrim(*s\wd1 + *s\wd1x) + " " + ~"here."
  *s\k = Len(*s\render)
Case 386 ; FORTRAN 994
  *s\phase = 387
  Text(*out, "I see no " + *s\render, 5199)
Case 387 ; FORTRAN 996
  *s\phase = 388
  *s\phase = 292 : Continue
