; Generated by tools/port_reference.py; audit against reference labels.
Case 518 ; FORTRAN 1213 label 8000
  *s\phase = 519
  *s\render = RTrim(*s\wd1 + *s\wd1x) + " " + ~"What?"
  *s\k = Len(*s\render)
Case 519 ; FORTRAN 1214
  *s\phase = 520
  Text(*out, *s\render, 8002)
Case 520 ; FORTRAN 1216
  *s\phase = 521
  *s\obj = 0
Case 521 ; FORTRAN 1217
  *s\phase = 522
  *s\phase = 294 : Continue
Case 522 ; FORTRAN 1221 label 8010
  *s\phase = 523
  If Bool(Bool(*s\atloc[*s\loc] = 0) Or Bool(*s\link[*s\atloc[*s\loc]] <> 0))
    *s\phase = 518 : Continue
  EndIf
Case 523 ; FORTRAN 1222
  *s\phase = 524
  *s\i = 1
Case 524 ; FORTRAN 1223
  *s\phase = 525
  If Bool(Bool(*s\dloc[*s\i] = *s\loc) And Bool(*s\dflag >= 2))
    *s\phase = 518 : Continue
  EndIf
Case 525 ; FORTRAN 1224 label 8012
  *s\phase = 526
  *s\i + 1
  If *s\i <= 5 : *s\phase = 524 : EndIf
Case 526 ; FORTRAN 1225
  *s\phase = 527
  *s\obj = *s\atloc[*s\loc]
Case 527 ; FORTRAN 1231 label 9010
  *s\phase = 528
  If Toting(*db, *s, *s\obj)
    *s\phase = 291 : Continue
  EndIf
Case 528 ; FORTRAN 1232
  *s\phase = 529
  *s\spk = 25
Case 529 ; FORTRAN 1233
  *s\phase = 530
  If Bool(Bool(*s\obj = *s\plant) And Bool(*s\prop[*s\plant] <= 0))
    *s\spk = 115
  EndIf
Case 530 ; FORTRAN 1234
  *s\phase = 531
  If Bool(Bool(*s\obj = *s\bear) And Bool(*s\prop[*s\bear] = 1))
    *s\spk = 169
  EndIf
Case 531 ; FORTRAN 1235
  *s\phase = 532
  If Bool(Bool(*s\obj = *s\chain) And Bool(*s\prop[*s\bear] <> 0))
    *s\spk = 170
  EndIf
Case 532 ; FORTRAN 1236
  *s\phase = 533
  If Bool(*s\fixed[*s\obj] <> 0)
    *s\phase = 291 : Continue
  EndIf
Case 533 ; FORTRAN 1237
  *s\phase = 534
  If Bool(Bool(*s\obj <> *s\water) And Bool(*s\obj <> *s\oil))
    *s\phase = 541 : Continue
  EndIf
Case 534 ; FORTRAN 1238
  *s\phase = 535
  If Bool(Here(*db, *s, *s\bottle) And Bool(Liq(*db, *s, 0) = *s\obj))
    *s\phase = 540 : Continue
  EndIf
Case 535 ; FORTRAN 1239
  *s\phase = 536
  *s\obj = *s\bottle
Case 536 ; FORTRAN 1240
  *s\phase = 537
  If Bool(Toting(*db, *s, *s\bottle) And Bool(*s\prop[*s\bottle] = 1))
    *s\phase = 863 : Continue
  EndIf
Case 537 ; FORTRAN 1241
  *s\phase = 538
  If Bool(*s\prop[*s\bottle] <> 1)
    *s\spk = 105
  EndIf
Case 538 ; FORTRAN 1242
  *s\phase = 539
  If Bool(Not Toting(*db, *s, *s\bottle))
    *s\spk = 104
  EndIf
Case 539 ; FORTRAN 1243
  *s\phase = 540
  *s\phase = 291 : Continue
Case 540 ; FORTRAN 1244 label 9018
  *s\phase = 541
  *s\obj = *s\bottle
Case 541 ; FORTRAN 1245 label 9017
  *s\phase = 542
  If Bool(*s\holdng < 7)
    *s\phase = 544 : Continue
  EndIf
Case 542 ; FORTRAN 1246
  *s\phase = 543
  Emit(*db, *out, 6, 92)
Case 543 ; FORTRAN 1247
  *s\phase = 544
  *s\phase = 292 : Continue
Case 544 ; FORTRAN 1248 label 9016
  *s\phase = 545
  If Bool(*s\obj <> *s\bird)
    *s\phase = 553 : Continue
  EndIf
Case 545 ; FORTRAN 1249
  *s\phase = 546
  If Bool(*s\prop[*s\bird] <> 0)
    *s\phase = 553 : Continue
  EndIf
Case 546 ; FORTRAN 1250
  *s\phase = 547
  If Bool(Not Toting(*db, *s, *s\rod))
    *s\phase = 549 : Continue
  EndIf
Case 547 ; FORTRAN 1251
  *s\phase = 548
  Emit(*db, *out, 6, 26)
Case 548 ; FORTRAN 1252
  *s\phase = 549
  *s\phase = 292 : Continue
Case 549 ; FORTRAN 1253 label 9013
  *s\phase = 550
  If Toting(*db, *s, *s\cage)
    *s\phase = 552 : Continue
  EndIf
Case 550 ; FORTRAN 1254
  *s\phase = 551
  Emit(*db, *out, 6, 27)
Case 551 ; FORTRAN 1255
  *s\phase = 552
  *s\phase = 292 : Continue
Case 552 ; FORTRAN 1256 label 9015
  *s\phase = 553
  *s\prop[*s\bird] = 1
Case 553 ; FORTRAN 1257 label 9014
  *s\phase = 554
  If Bool((Bool(Bool(*s\obj = *s\bird) Or Bool(*s\obj = *s\cage))) And Bool(*s\prop[*s\bird] <> 0))
    Carry(*s, ((*s\bird + *s\cage) - *s\obj), *s\loc)
  EndIf
Case 554 ; FORTRAN 1259
  *s\phase = 555
  Carry(*s, *s\obj, *s\loc)
Case 555 ; FORTRAN 1260
  *s\phase = 556
  *s\k = Liq(*db, *s, 0)
Case 556 ; FORTRAN 1261
  *s\phase = 557
  If Bool(Bool(*s\obj = *s\bottle) And Bool(*s\k <> 0))
    *s\place[*s\k] = (-1)
  EndIf
Case 557 ; FORTRAN 1262
  *s\phase = 558
  *s\phase = 289 : Continue
Case 558 ; FORTRAN 1268 label 9020
  *s\phase = 559
  If Bool(Bool(Toting(*db, *s, *s\rod2) And Bool(*s\obj = *s\rod)) And Bool(Not Toting(*db, *s, *s\rod)))
    *s\obj = *s\rod2
  EndIf
Case 559 ; FORTRAN 1269
  *s\phase = 560
  If Bool(Not Toting(*db, *s, *s\obj))
    *s\phase = 291 : Continue
  EndIf
Case 560 ; FORTRAN 1270
  *s\phase = 561
  If Bool(Bool(*s\obj <> *s\bird) Or Bool(Not Here(*db, *s, *s\snake)))
    *s\phase = 572 : Continue
  EndIf
Case 561 ; FORTRAN 1271
  *s\phase = 562
  Emit(*db, *out, 6, 30)
Case 562 ; FORTRAN 1272
  *s\phase = 563
  If *s\closed
    *s\phase = 1038 : Continue
  EndIf
Case 563 ; FORTRAN 1273
  *s\phase = 564
  Dstroy(*s, *s\snake)
Case 564 ; FORTRAN 1275
  *s\phase = 565
  *s\prop[*s\snake] = 1
Case 565 ; FORTRAN 1276 label 9021
  *s\phase = 566
  *s\k = Liq(*db, *s, 0)
Case 566 ; FORTRAN 1277
  *s\phase = 567
  If Bool(*s\k = *s\obj)
    *s\obj = *s\bottle
  EndIf
Case 567 ; FORTRAN 1278
  *s\phase = 568
  If Bool(Bool(*s\obj = *s\bottle) And Bool(*s\k <> 0))
    *s\place[*s\k] = 0
  EndIf
Case 568 ; FORTRAN 1279
  *s\phase = 569
  If Bool(Bool(*s\obj = *s\cage) And Bool(*s\prop[*s\bird] <> 0))
    Drop(*s, *s\bird, *s\loc)
  EndIf
Case 569 ; FORTRAN 1280
  *s\phase = 570
  If Bool(*s\obj = *s\bird)
    *s\prop[*s\bird] = 0
  EndIf
Case 570 ; FORTRAN 1281
  *s\phase = 571
  Drop(*s, *s\obj, *s\loc)
Case 571 ; FORTRAN 1282
  *s\phase = 572
  *s\phase = 292 : Continue
Case 572 ; FORTRAN 1284 label 9024
  *s\phase = 573
  If Bool(Bool(*s\obj <> *s\coins) Or Bool(Not Here(*db, *s, *s\vend)))
    *s\phase = 577 : Continue
  EndIf
Case 573 ; FORTRAN 1285
  *s\phase = 574
  Dstroy(*s, *s\coins)
Case 574 ; FORTRAN 1286
  *s\phase = 575
  Drop(*s, *s\batter, *s\loc)
Case 575 ; FORTRAN 1287
  *s\phase = 576
  Emit(*db, *out, 5, *s\batter, 0)
Case 576 ; FORTRAN 1288
  *s\phase = 577
  *s\phase = 292 : Continue
Case 577 ; FORTRAN 1290 label 9025
  *s\phase = 578
  If Bool(Bool(Bool(*s\obj <> *s\bird) Or Bool(Not At(*db, *s, *s\dragon))) Or Bool(*s\prop[*s\dragon] <> 0))
    *s\phase = 583 : Continue
  EndIf
Case 578 ; FORTRAN 1291
  *s\phase = 579
  Emit(*db, *out, 6, 154)
Case 579 ; FORTRAN 1292
  *s\phase = 580
  Dstroy(*s, *s\bird)
Case 580 ; FORTRAN 1293
  *s\phase = 581
  *s\prop[*s\bird] = 0
Case 581 ; FORTRAN 1294
  *s\phase = 582
  If Bool(*s\place[*s\snake] = *db\plac[*s\snake])
    *s\tally2 = (*s\tally2 + 1)
  EndIf
Case 582 ; FORTRAN 1295
  *s\phase = 583
  *s\phase = 292 : Continue
Case 583 ; FORTRAN 1297 label 9026
  *s\phase = 584
  If Bool(Bool(*s\obj <> *s\bear) Or Bool(Not At(*db, *s, *s\troll)))
    *s\phase = 592 : Continue
  EndIf
Case 584 ; FORTRAN 1298
  *s\phase = 585
  Emit(*db, *out, 6, 163)
Case 585 ; FORTRAN 1299
  *s\phase = 586
  Move(*s, *s\troll, 0)
Case 586 ; FORTRAN 1300
  *s\phase = 587
  Move(*s, (*s\troll + 100), 0)
Case 587 ; FORTRAN 1301
  *s\phase = 588
  Move(*s, *s\troll2, *db\plac[*s\troll])
Case 588 ; FORTRAN 1302
  *s\phase = 589
  Move(*s, (*s\troll2 + 100), *db\fixd[*s\troll])
Case 589 ; FORTRAN 1303
  *s\phase = 590
  Juggle(*s, *s\chasm)
Case 590 ; FORTRAN 1304
  *s\phase = 591
  *s\prop[*s\troll] = 2
Case 591 ; FORTRAN 1305
  *s\phase = 592
  *s\phase = 565 : Continue
Case 592 ; FORTRAN 1307 label 9027
  *s\phase = 593
  If Bool(Bool(*s\obj = *s\vase) And Bool(*s\loc <> *db\plac[*s\pillow]))
    *s\phase = 595 : Continue
  EndIf
Case 593 ; FORTRAN 1308
  *s\phase = 594
  Emit(*db, *out, 6, 54)
Case 594 ; FORTRAN 1309
  *s\phase = 595
  *s\phase = 565 : Continue
Case 595 ; FORTRAN 1311 label 9028
  *s\phase = 596
  *s\prop[*s\vase] = 2
Case 596 ; FORTRAN 1312
  *s\phase = 597
  If At(*db, *s, *s\pillow)
    *s\prop[*s\vase] = 0
  EndIf
Case 597 ; FORTRAN 1313
  *s\phase = 598
  Emit(*db, *out, 5, *s\vase, (*s\prop[*s\vase] + 1))
Case 598 ; FORTRAN 1314
  *s\phase = 599
  If Bool(*s\prop[*s\vase] <> 0)
    *s\fixed[*s\vase] = (-1)
  EndIf
Case 599 ; FORTRAN 1315
  *s\phase = 600
  *s\phase = 565 : Continue
Case 600 ; FORTRAN 1319 label 9030
  *s\phase = 601
  *s\render = RTrim(*s\wd2 + *s\wd2x) + ~"\"."
  *s\k = Len(*s\render)
Case 601 ; FORTRAN 1320
  *s\phase = 602
  If Bool(*s\wd2 = "")
    *s\render = RTrim(*s\wd1 + *s\wd1x) + ~"\"."
    *s\k = Len(*s\render)
  EndIf
Case 602 ; FORTRAN 1321
  *s\phase = 603
  If Bool(*s\wd2 <> "")
    *s\wd1 = *s\wd2
  EndIf
Case 603 ; FORTRAN 1322
  *s\phase = 604
  *s\i = Vocab(*db, *s\wd1, (-1))
Case 604 ; FORTRAN 1323
  *s\phase = 605
  If Bool(Bool(Bool(Bool(*s\i = 62) Or Bool(*s\i = 65)) Or Bool(*s\i = 71)) Or Bool(*s\i = 2025))
    *s\phase = 607 : Continue
  EndIf
Case 605 ; FORTRAN 1324
  *s\phase = 606
  Text(*out, "Okay, " + Chr(34) + *s\render, 9032)
Case 606 ; FORTRAN 1326
  *s\phase = 607
  *s\phase = 292 : Continue
Case 607 ; FORTRAN 1328 label 9035
  *s\phase = 608
  *s\wd2 = ""
Case 608 ; FORTRAN 1329
  *s\phase = 609
  *s\obj = 0
Case 609 ; FORTRAN 1330
  *s\phase = 610
  *s\phase = 334 : Continue
Case 610 ; FORTRAN 1334 label 8040
  *s\phase = 611
  *s\spk = 28
Case 611 ; FORTRAN 1335
  *s\phase = 612
  If Here(*db, *s, *s\clam)
    *s\obj = *s\clam
  EndIf
Case 612 ; FORTRAN 1336
  *s\phase = 613
  If Here(*db, *s, *s\oyster)
    *s\obj = *s\oyster
  EndIf
Case 613 ; FORTRAN 1337
  *s\phase = 614
  If At(*db, *s, *s\door)
    *s\obj = *s\door
  EndIf
Case 614 ; FORTRAN 1338
  *s\phase = 615
  If At(*db, *s, *s\grate)
    *s\obj = *s\grate
  EndIf
Case 615 ; FORTRAN 1339
  *s\phase = 616
  If Bool(Bool(*s\obj <> 0) And Here(*db, *s, *s\chain))
    *s\phase = 518 : Continue
  EndIf
Case 616 ; FORTRAN 1340
  *s\phase = 617
  If Here(*db, *s, *s\chain)
    *s\obj = *s\chain
  EndIf
Case 617 ; FORTRAN 1341
  *s\phase = 618
  If Bool(*s\obj = 0)
    *s\phase = 291 : Continue
  EndIf
Case 618 ; FORTRAN 1345 label 9040
  *s\phase = 619
  If Bool(Bool(*s\obj = *s\clam) Or Bool(*s\obj = *s\oyster))
    *s\phase = 636 : Continue
  EndIf
Case 619 ; FORTRAN 1346
  *s\phase = 620
  If Bool(*s\obj = *s\door)
    *s\spk = 111
  EndIf
Case 620 ; FORTRAN 1347
  *s\phase = 621
  If Bool(Bool(*s\obj = *s\door) And Bool(*s\prop[*s\door] = 1))
    *s\spk = 54
  EndIf
Case 621 ; FORTRAN 1348
  *s\phase = 622
  If Bool(*s\obj = *s\cage)
    *s\spk = 32
  EndIf
Case 622 ; FORTRAN 1349
  *s\phase = 623
  If Bool(*s\obj = *s\keys)
    *s\spk = 55
  EndIf
Case 623 ; FORTRAN 1350
  *s\phase = 624
  If Bool(Bool(*s\obj = *s\grate) Or Bool(*s\obj = *s\chain))
    *s\spk = 31
  EndIf
Case 624 ; FORTRAN 1351
  *s\phase = 625
  If Bool(Bool(*s\spk <> 31) Or Bool(Not Here(*db, *s, *s\keys)))
    *s\phase = 291 : Continue
  EndIf
Case 625 ; FORTRAN 1352
  *s\phase = 626
  If Bool(*s\obj = *s\chain)
    *s\phase = 647 : Continue
  EndIf
Case 626 ; FORTRAN 1353
  *s\phase = 627
  If Bool(Not *s\closng)
    *s\phase = 631 : Continue
  EndIf
Case 627 ; FORTRAN 1354
  *s\phase = 628
  *s\k = 130
Case 628 ; FORTRAN 1355
  *s\phase = 629
  If Bool(Not *s\panic)
    *s\clock2 = 15
  EndIf
Case 629 ; FORTRAN 1356
  *s\phase = 630
  *s\panic = 1
Case 630 ; FORTRAN 1357
  *s\phase = 631
  *s\phase = 290 : Continue
Case 631 ; FORTRAN 1359 label 9043
  *s\phase = 632
  *s\k = (34 + *s\prop[*s\grate])
Case 632 ; FORTRAN 1360
  *s\phase = 633
  *s\prop[*s\grate] = 1
Case 633 ; FORTRAN 1361
  *s\phase = 634
  If Bool(*s\verb = *s\lock)
    *s\prop[*s\grate] = 0
  EndIf
Case 634 ; FORTRAN 1362
  *s\phase = 635
  *s\k = (*s\k + (2 * *s\prop[*s\grate]))
Case 635 ; FORTRAN 1363
  *s\phase = 636
  *s\phase = 290 : Continue
Case 636 ; FORTRAN 1366 label 9046
  *s\phase = 637
  *s\k = 0
Case 637 ; FORTRAN 1367
  *s\phase = 638
  If Bool(*s\obj = *s\oyster)
    *s\k = 1
  EndIf
Case 638 ; FORTRAN 1368
  *s\phase = 639
  *s\spk = (124 + *s\k)
Case 639 ; FORTRAN 1369
  *s\phase = 640
  If Toting(*db, *s, *s\obj)
    *s\spk = (120 + *s\k)
  EndIf
Case 640 ; FORTRAN 1370
  *s\phase = 641
  If Bool(Not Toting(*db, *s, *s\tridnt))
    *s\spk = (122 + *s\k)
  EndIf
Case 641 ; FORTRAN 1371
  *s\phase = 642
  If Bool(*s\verb = *s\lock)
    *s\spk = 61
  EndIf
Case 642 ; FORTRAN 1372
  *s\phase = 643
  If Bool(*s\spk <> 124)
    *s\phase = 291 : Continue
  EndIf
Case 643 ; FORTRAN 1373
  *s\phase = 644
  Dstroy(*s, *s\clam)
Case 644 ; FORTRAN 1374
  *s\phase = 645
  Drop(*s, *s\oyster, *s\loc)
Case 645 ; FORTRAN 1375
  *s\phase = 646
  Drop(*s, *s\pearl, 105)
Case 646 ; FORTRAN 1376
  *s\phase = 647
  *s\phase = 291 : Continue
Case 647 ; FORTRAN 1379 label 9048
  *s\phase = 648
  If Bool(*s\verb = *s\lock)
    *s\phase = 657 : Continue
  EndIf
Case 648 ; FORTRAN 1380
  *s\phase = 649
  *s\spk = 171
Case 649 ; FORTRAN 1381
  *s\phase = 650
  If Bool(*s\prop[*s\bear] = 0)
    *s\spk = 41
  EndIf
Case 650 ; FORTRAN 1382
  *s\phase = 651
  If Bool(*s\prop[*s\chain] = 0)
    *s\spk = 37
  EndIf
Case 651 ; FORTRAN 1383
  *s\phase = 652
  If Bool(*s\spk <> 171)
    *s\phase = 291 : Continue
  EndIf
Case 652 ; FORTRAN 1384
  *s\phase = 653
  *s\prop[*s\chain] = 0
Case 653 ; FORTRAN 1385
  *s\phase = 654
  *s\fixed[*s\chain] = 0
Case 654 ; FORTRAN 1386
  *s\phase = 655
  If Bool(*s\prop[*s\bear] <> 3)
    *s\prop[*s\bear] = 2
  EndIf
Case 655 ; FORTRAN 1387
  *s\phase = 656
  *s\fixed[*s\bear] = (2 - *s\prop[*s\bear])
Case 656 ; FORTRAN 1388
  *s\phase = 657
  *s\phase = 291 : Continue
Case 657 ; FORTRAN 1390 label 9049
  *s\phase = 658
  *s\spk = 172
Case 658 ; FORTRAN 1391
  *s\phase = 659
  If Bool(*s\prop[*s\chain] <> 0)
    *s\spk = 34
  EndIf
Case 659 ; FORTRAN 1392
  *s\phase = 660
  If Bool(*s\loc <> *db\plac[*s\chain])
    *s\spk = 173
  EndIf
Case 660 ; FORTRAN 1393
  *s\phase = 661
  If Bool(*s\spk <> 172)
    *s\phase = 291 : Continue
  EndIf
Case 661 ; FORTRAN 1394
  *s\phase = 662
  *s\prop[*s\chain] = 2
Case 662 ; FORTRAN 1395
  *s\phase = 663
  If Toting(*db, *s, *s\chain)
    Drop(*s, *s\chain, *s\loc)
  EndIf
Case 663 ; FORTRAN 1396
  *s\phase = 664
  *s\fixed[*s\chain] = (-1)
Case 664 ; FORTRAN 1397
  *s\phase = 665
  *s\phase = 291 : Continue
Case 665 ; FORTRAN 1401 label 9070
  *s\phase = 666
  If Bool(Not Here(*db, *s, *s\lamp))
    *s\phase = 291 : Continue
  EndIf
Case 666 ; FORTRAN 1402
  *s\phase = 667
  *s\spk = 184
Case 667 ; FORTRAN 1403
  *s\phase = 668
  If Bool(*s\limit < 0)
    *s\phase = 291 : Continue
  EndIf
Case 668 ; FORTRAN 1404
  *s\phase = 669
  *s\prop[*s\lamp] = 1
Case 669 ; FORTRAN 1405
  *s\phase = 670
  Emit(*db, *out, 6, 39)
Case 670 ; FORTRAN 1406
  *s\phase = 671
  If *s\wzdark
    *s\phase = 260 : Continue
  EndIf
Case 671 ; FORTRAN 1407
  *s\phase = 672
  *s\phase = 292 : Continue
Case 672 ; FORTRAN 1411 label 9080
  *s\phase = 673
  If Bool(Not Here(*db, *s, *s\lamp))
    *s\phase = 291 : Continue
  EndIf
Case 673 ; FORTRAN 1412
  *s\phase = 674
  *s\prop[*s\lamp] = 0
Case 674 ; FORTRAN 1413
  *s\phase = 675
  Emit(*db, *out, 6, 40)
Case 675 ; FORTRAN 1414
  *s\phase = 676
  If Dark(*db, *s, 0)
    Emit(*db, *out, 6, 16)
  EndIf
Case 676 ; FORTRAN 1415
  *s\phase = 677
  *s\phase = 292 : Continue
Case 677 ; FORTRAN 1419 label 9090
  *s\phase = 678
  If Bool((Bool(Not Toting(*db, *s, *s\obj))) And (Bool(Bool(*s\obj <> *s\rod) Or Bool(Not Toting(*db, *s, *s\rod2)))))
    *s\spk = 29
  EndIf
Case 678 ; FORTRAN 1421
  *s\phase = 679
  If Bool(Bool(Bool(Bool(*s\obj <> *s\rod) Or Bool(Not At(*db, *s, *s\fissur))) Or Bool(Not Toting(*db, *s, *s\obj))) Or *s\closng)
    *s\phase = 291 : Continue
  EndIf
Case 679 ; FORTRAN 1423
  *s\phase = 680
  *s\prop[*s\fissur] = (1 - *s\prop[*s\fissur])
Case 680 ; FORTRAN 1424
  *s\phase = 681
  Emit(*db, *out, 5, *s\fissur, (2 - *s\prop[*s\fissur]))
Case 681 ; FORTRAN 1425
  *s\phase = 682
  *s\phase = 292 : Continue
Case 682 ; FORTRAN 1431 label 9120
  *s\phase = 683
  *s\i = 1
Case 683 ; FORTRAN 1432
  *s\phase = 684
  If Bool(Bool(*s\dloc[*s\i] = *s\loc) And Bool(*s\dflag >= 2))
    *s\phase = 686 : Continue
  EndIf
Case 684 ; FORTRAN 1433 label 9121
  *s\phase = 685
  *s\i + 1
  If *s\i <= 5 : *s\phase = 683 : EndIf
Case 685 ; FORTRAN 1434
  *s\phase = 686
  *s\i = 0
Case 686 ; FORTRAN 1435 label 9122
  *s\phase = 687
  If Bool(*s\obj <> 0)
    *s\phase = 697 : Continue
  EndIf
Case 687 ; FORTRAN 1436
  *s\phase = 688
  If Bool(*s\i <> 0)
    *s\obj = *s\dwarf
  EndIf
Case 688 ; FORTRAN 1437
  *s\phase = 689
  If Here(*db, *s, *s\snake)
    *s\obj = ((*s\obj * 100) + *s\snake)
  EndIf
Case 689 ; FORTRAN 1438
  *s\phase = 690
  If Bool(At(*db, *s, *s\dragon) And Bool(*s\prop[*s\dragon] = 0))
    *s\obj = ((*s\obj * 100) + *s\dragon)
  EndIf
Case 690 ; FORTRAN 1439
  *s\phase = 691
  If At(*db, *s, *s\troll)
    *s\obj = ((*s\obj * 100) + *s\troll)
  EndIf
Case 691 ; FORTRAN 1440
  *s\phase = 692
  If Bool(Here(*db, *s, *s\bear) And Bool(*s\prop[*s\bear] = 0))
    *s\obj = ((*s\obj * 100) + *s\bear)
  EndIf
Case 692 ; FORTRAN 1441
  *s\phase = 693
  If Bool(*s\obj > 100)
    *s\phase = 518 : Continue
  EndIf
Case 693 ; FORTRAN 1442
  *s\phase = 694
  If Bool(*s\obj <> 0)
    *s\phase = 697 : Continue
  EndIf
Case 694 ; FORTRAN 1444
  *s\phase = 695
  If Bool(Here(*db, *s, *s\bird) And Bool(*s\verb <> *s\throw))
    *s\obj = *s\bird
  EndIf
Case 695 ; FORTRAN 1446
  *s\phase = 696
  If Bool(Here(*db, *s, *s\clam) Or Here(*db, *s, *s\oyster))
    *s\obj = ((100 * *s\obj) + *s\clam)
  EndIf
Case 696 ; FORTRAN 1447
  *s\phase = 697
  If Bool(*s\obj > 100)
    *s\phase = 518 : Continue
  EndIf
Case 697 ; FORTRAN 1448 label 9124
  *s\phase = 698
  If Bool(*s\obj <> *s\bird)
    *s\phase = 704 : Continue
  EndIf
Case 698 ; FORTRAN 1449
  *s\phase = 699
  *s\spk = 137
Case 699 ; FORTRAN 1450
  *s\phase = 700
  If *s\closed
    *s\phase = 291 : Continue
  EndIf
Case 700 ; FORTRAN 1451
  *s\phase = 701
  Dstroy(*s, *s\bird)
Case 701 ; FORTRAN 1452
  *s\phase = 702
  *s\prop[*s\bird] = 0
Case 702 ; FORTRAN 1453
  *s\phase = 703
  If Bool(*s\place[*s\snake] = *db\plac[*s\snake])
    *s\tally2 = (*s\tally2 + 1)
  EndIf
Case 703 ; FORTRAN 1454
  *s\phase = 704
  *s\spk = 45
Case 704 ; FORTRAN 1455 label 9125
  *s\phase = 705
  If Bool(*s\obj = 0)
    *s\spk = 44
  EndIf
Case 705 ; FORTRAN 1456
  *s\phase = 706
  If Bool(Bool(*s\obj = *s\clam) Or Bool(*s\obj = *s\oyster))
    *s\spk = 150
  EndIf
Case 706 ; FORTRAN 1457
  *s\phase = 707
  If Bool(*s\obj = *s\snake)
    *s\spk = 46
  EndIf
Case 707 ; FORTRAN 1458
  *s\phase = 708
  If Bool(*s\obj = *s\dwarf)
    *s\spk = 49
  EndIf
Case 708 ; FORTRAN 1459
  *s\phase = 709
  If Bool(Bool(*s\obj = *s\dwarf) And *s\closed)
    *s\phase = 1038 : Continue
  EndIf
Case 709 ; FORTRAN 1460
  *s\phase = 710
  If Bool(*s\obj = *s\dragon)
    *s\spk = 167
  EndIf
Case 710 ; FORTRAN 1461
  *s\phase = 711
  If Bool(*s\obj = *s\troll)
    *s\spk = 157
  EndIf
Case 711 ; FORTRAN 1462
  *s\phase = 712
  If Bool(*s\obj = *s\bear)
    *s\spk = (165 + IDiv(((*s\prop[*s\bear] + 1)), 2))
  EndIf
Case 712 ; FORTRAN 1463
  *s\phase = 713
  If Bool(Bool(*s\obj <> *s\dragon) Or Bool(*s\prop[*s\dragon] <> 0))
    *s\phase = 291 : Continue
  EndIf
Case 713 ; FORTRAN 1467
  *s\phase = 714
  Emit(*db, *out, 6, 49)
Case 714 ; FORTRAN 1468
  *s\phase = 715
  *s\verb = 0
Case 715 ; FORTRAN 1469
  *s\phase = 716
  *s\obj = 0
Case 716 ; FORTRAN 1470
  *s\phase = 717
  *s\awaiting = 1 : *out\inputMode = #Command : ProcedureReturn
Case 717 ; FORTRAN 1471
  *s\phase = 718
  If Bool(Bool(*s\wd1 <> ~"Y") And Bool(*s\wd1 <> ~"YES"))
    *s\phase = 310 : Continue
  EndIf
Case 718 ; FORTRAN 1472
  *s\phase = 719
  Emit(*db, *out, 5, *s\dragon, 1)
Case 719 ; FORTRAN 1473
  *s\phase = 720
  *s\prop[*s\dragon] = 2
Case 720 ; FORTRAN 1474
  *s\phase = 721
  *s\prop[*s\rug] = 0
Case 721 ; FORTRAN 1475
  *s\phase = 722
  *s\k = IDiv(((*db\plac[*s\dragon] + *db\fixd[*s\dragon])), 2)
Case 722 ; FORTRAN 1476
  *s\phase = 723
  Move(*s, (*s\dragon + 100), (-1))
Case 723 ; FORTRAN 1477
  *s\phase = 724
  Move(*s, (*s\rug + 100), 0)
Case 724 ; FORTRAN 1478
  *s\phase = 725
  Move(*s, *s\dragon, *s\k)
Case 725 ; FORTRAN 1479
  *s\phase = 726
  Move(*s, *s\rug, *s\k)
Case 726 ; FORTRAN 1480
  *s\phase = 727
  *s\obj = 1
Case 727 ; FORTRAN 1481
  *s\phase = 728
  *s\idondx = *s\obj
Case 728 ; FORTRAN 1482
  *s\phase = 729
  If Bool(Bool(*s\place[*s\idondx] = *db\plac[*s\dragon]) Or Bool(*s\place[*s\idondx] = *db\fixd[*s\dragon]))
    Move(*s, *s\idondx, *s\k)
  EndIf
Case 729 ; FORTRAN 1485 label 9126
  *s\phase = 730
  *s\obj + 1
  If *s\obj <= 100 : *s\phase = 727 : EndIf
Case 730 ; FORTRAN 1486
  *s\phase = 731
  *s\loc = *s\k
Case 731 ; FORTRAN 1487
  *s\phase = 732
  *s\k = *s\null
Case 732 ; FORTRAN 1488
  *s\phase = 733
  *s\phase = 388 : Continue
Case 733 ; FORTRAN 1493 label 9130
  *s\phase = 734
  If Bool(Bool(*s\obj = *s\bottle) Or Bool(*s\obj = 0))
    *s\obj = Liq(*db, *s, 0)
  EndIf
Case 734 ; FORTRAN 1494
  *s\phase = 735
  If Bool(*s\obj = 0)
    *s\phase = 518 : Continue
  EndIf
Case 735 ; FORTRAN 1495
  *s\phase = 736
  If Bool(Not Toting(*db, *s, *s\obj))
    *s\phase = 291 : Continue
  EndIf
Case 736 ; FORTRAN 1496
  *s\phase = 737
  *s\spk = 78
Case 737 ; FORTRAN 1497
  *s\phase = 738
  If Bool(Bool(*s\obj <> *s\oil) And Bool(*s\obj <> *s\water))
    *s\phase = 291 : Continue
  EndIf
Case 738 ; FORTRAN 1498
  *s\phase = 739
  *s\prop[*s\bottle] = 1
Case 739 ; FORTRAN 1499
  *s\phase = 740
  *s\place[*s\obj] = 0
Case 740 ; FORTRAN 1500
  *s\phase = 741
  *s\spk = 77
Case 741 ; FORTRAN 1501
  *s\phase = 742
  If Bool(Not (Bool(At(*db, *s, *s\plant) Or At(*db, *s, *s\door))))
    *s\phase = 291 : Continue
  EndIf
Case 742 ; FORTRAN 1503
  *s\phase = 743
  If At(*db, *s, *s\door)
    *s\phase = 750 : Continue
  EndIf
Case 743 ; FORTRAN 1504
  *s\phase = 744
  *s\spk = 112
Case 744 ; FORTRAN 1505
  *s\phase = 745
  If Bool(*s\obj <> *s\water)
    *s\phase = 291 : Continue
  EndIf
Case 745 ; FORTRAN 1506
  *s\phase = 746
  Emit(*db, *out, 5, *s\plant, (*s\prop[*s\plant] + 1))
Case 746 ; FORTRAN 1507
  *s\phase = 747
  *s\prop[*s\plant] = ((*s\prop[*s\plant] + 2) % 6)
Case 747 ; FORTRAN 1508
  *s\phase = 748
  *s\prop[*s\plant2] = IDiv(*s\prop[*s\plant], 2)
Case 748 ; FORTRAN 1509
  *s\phase = 749
  *s\k = *s\null
Case 749 ; FORTRAN 1510
  *s\phase = 750
  *s\phase = 388 : Continue
Case 750 ; FORTRAN 1512 label 9132
  *s\phase = 751
  *s\prop[*s\door] = 0
Case 751 ; FORTRAN 1513
  *s\phase = 752
  If Bool(*s\obj = *s\oil)
    *s\prop[*s\door] = 1
  EndIf
Case 752 ; FORTRAN 1514
  *s\phase = 753
  *s\spk = (113 + *s\prop[*s\door])
Case 753 ; FORTRAN 1515
  *s\phase = 754
  *s\phase = 291 : Continue
Case 754 ; FORTRAN 1520 label 8140
  *s\phase = 755
  If Bool(Not Here(*db, *s, *s\food))
    *s\phase = 518 : Continue
  EndIf
Case 755 ; FORTRAN 1521 label 8142
  *s\phase = 756
  Dstroy(*s, *s\food)
Case 756 ; FORTRAN 1522
  *s\phase = 757
  *s\spk = 72
Case 757 ; FORTRAN 1523
  *s\phase = 758
  *s\phase = 291 : Continue
Case 758 ; FORTRAN 1525 label 9140
  *s\phase = 759
  If Bool(*s\obj = *s\food)
    *s\phase = 755 : Continue
  EndIf
Case 759 ; FORTRAN 1526
  *s\phase = 760
  If Bool(Bool(Bool(Bool(Bool(Bool(Bool(Bool(*s\obj = *s\bird) Or Bool(*s\obj = *s\snake)) Or Bool(*s\obj = *s\clam)) Or Bool(*s\obj = *s\oyster)) Or Bool(*s\obj = *s\dwarf)) Or Bool(*s\obj = *s\dragon)) Or Bool(*s\obj = *s\troll)) Or Bool(*s\obj = *s\bear))
    *s\spk = 71
  EndIf
Case 760 ; FORTRAN 1529
  *s\phase = 761
  *s\phase = 291 : Continue
Case 761 ; FORTRAN 1534 label 9150
  *s\phase = 762
  If Bool(Bool(Bool(*s\obj = 0) And Bool(Liqloc(*db, *s, *s\loc) <> *s\water)) And (Bool(Bool(Liq(*db, *s, 0) <> *s\water) Or Bool(Not Here(*db, *s, *s\bottle)))))
    *s\phase = 518 : Continue
  EndIf
Case 762 ; FORTRAN 1536
  *s\phase = 763
  If Bool(Bool(*s\obj <> 0) And Bool(*s\obj <> *s\water))
    *s\spk = 110
  EndIf
Case 763 ; FORTRAN 1537
  *s\phase = 764
  If Bool(Bool(Bool(*s\spk = 110) Or Bool(Liq(*db, *s, 0) <> *s\water)) Or Bool(Not Here(*db, *s, *s\bottle)))
    *s\phase = 291 : Continue
  EndIf
Case 764 ; FORTRAN 1538
  *s\phase = 765
  *s\prop[*s\bottle] = 1
Case 765 ; FORTRAN 1539
  *s\phase = 766
  *s\place[*s\water] = 0
Case 766 ; FORTRAN 1540
  *s\phase = 767
  *s\spk = 74
Case 767 ; FORTRAN 1541
  *s\phase = 768
  *s\phase = 291 : Continue
Case 768 ; FORTRAN 1545 label 9160
  *s\phase = 769
  If Bool(*s\obj <> *s\lamp)
    *s\spk = 76
  EndIf
Case 769 ; FORTRAN 1546
  *s\phase = 770
  *s\phase = 291 : Continue
Case 770 ; FORTRAN 1552 label 9170
  *s\phase = 771
  If Bool(Bool(Toting(*db, *s, *s\rod2) And Bool(*s\obj = *s\rod)) And Bool(Not Toting(*db, *s, *s\rod)))
    *s\obj = *s\rod2
  EndIf
Case 771 ; FORTRAN 1553
  *s\phase = 772
  If Bool(Not Toting(*db, *s, *s\obj))
    *s\phase = 291 : Continue
  EndIf
Case 772 ; FORTRAN 1554
  *s\phase = 773
  If Bool(Bool(Bool(*s\obj >= 50) And Bool(*s\obj <= 79)) And At(*db, *s, *s\troll))
    *s\phase = 804 : Continue
  EndIf
Case 773 ; FORTRAN 1555
  *s\phase = 774
  If Bool(Bool(*s\obj = *s\food) And Here(*db, *s, *s\bear))
    *s\phase = 802 : Continue
  EndIf
Case 774 ; FORTRAN 1556
  *s\phase = 775
  If Bool(*s\obj <> *s\axe)
    *s\phase = 558 : Continue
  EndIf
Case 775 ; FORTRAN 1557
  *s\phase = 776
  *s\i = 1
Case 776 ; FORTRAN 1559
  *s\phase = 777
  If Bool(*s\dloc[*s\i] = *s\loc)
    *s\phase = 785 : Continue
  EndIf
Case 777 ; FORTRAN 1560 label 9171
  *s\phase = 778
  *s\i + 1
  If *s\i <= 5 : *s\phase = 776 : EndIf
Case 778 ; FORTRAN 1561
  *s\phase = 779
  *s\spk = 152
Case 779 ; FORTRAN 1562
  *s\phase = 780
  If Bool(At(*db, *s, *s\dragon) And Bool(*s\prop[*s\dragon] = 0))
    *s\phase = 792 : Continue
  EndIf
Case 780 ; FORTRAN 1563
  *s\phase = 781
  *s\spk = 158
Case 781 ; FORTRAN 1564
  *s\phase = 782
  If At(*db, *s, *s\troll)
    *s\phase = 792 : Continue
  EndIf
Case 782 ; FORTRAN 1565
  *s\phase = 783
  If Bool(Here(*db, *s, *s\bear) And Bool(*s\prop[*s\bear] = 0))
    *s\phase = 796 : Continue
  EndIf
Case 783 ; FORTRAN 1566
  *s\phase = 784
  *s\obj = 0
Case 784 ; FORTRAN 1567
  *s\phase = 785
  *s\phase = 682 : Continue
Case 785 ; FORTRAN 1569 label 9172
  *s\phase = 786
  *s\spk = 48
Case 786 ; FORTRAN 1571
  *s\phase = 787
  If Bool(Bool(RandomRange(*s, 3) = 0) Or Bool(*s\saved <> (-1)))
    *s\phase = 792 : Continue
  EndIf
Case 787 ; FORTRAN 1572
  *s\phase = 788
  *s\dseen[*s\i] = 0
Case 788 ; FORTRAN 1573
  *s\phase = 789
  *s\dloc[*s\i] = 0
Case 789 ; FORTRAN 1574
  *s\phase = 790
  *s\spk = 47
Case 790 ; FORTRAN 1575
  *s\phase = 791
  *s\dkill = (*s\dkill + 1)
Case 791 ; FORTRAN 1576
  *s\phase = 792
  If Bool(*s\dkill = 1)
    *s\spk = 149
  EndIf
Case 792 ; FORTRAN 1577 label 9175
  *s\phase = 793
  Emit(*db, *out, 6, *s\spk)
Case 793 ; FORTRAN 1578
  *s\phase = 794
  Drop(*s, *s\axe, *s\loc)
Case 794 ; FORTRAN 1579
  *s\phase = 795
  *s\k = *s\null
Case 795 ; FORTRAN 1580
  *s\phase = 796
  *s\phase = 388 : Continue
Case 796 ; FORTRAN 1583 label 9176
  *s\phase = 797
  *s\spk = 164
Case 797 ; FORTRAN 1584
  *s\phase = 798
  Drop(*s, *s\axe, *s\loc)
Case 798 ; FORTRAN 1585
  *s\phase = 799
  *s\fixed[*s\axe] = (-1)
Case 799 ; FORTRAN 1586
  *s\phase = 800
  *s\prop[*s\axe] = 1
Case 800 ; FORTRAN 1587
  *s\phase = 801
  Juggle(*s, *s\bear)
Case 801 ; FORTRAN 1588
  *s\phase = 802
  *s\phase = 291 : Continue
Case 802 ; FORTRAN 1591 label 9177
  *s\phase = 803
  *s\obj = *s\bear
Case 803 ; FORTRAN 1592
  *s\phase = 804
  *s\phase = 833 : Continue
Case 804 ; FORTRAN 1594 label 9178
  *s\phase = 805
  *s\spk = 159
Case 805 ; FORTRAN 1596
  *s\phase = 806
  Drop(*s, *s\obj, 0)
Case 806 ; FORTRAN 1597
  *s\phase = 807
  Move(*s, *s\troll, 0)
Case 807 ; FORTRAN 1598
  *s\phase = 808
  Move(*s, (*s\troll + 100), 0)
Case 808 ; FORTRAN 1599
  *s\phase = 809
  Drop(*s, *s\troll2, *db\plac[*s\troll])
Case 809 ; FORTRAN 1600
  *s\phase = 810
  Drop(*s, (*s\troll2 + 100), *db\fixd[*s\troll])
Case 810 ; FORTRAN 1601
  *s\phase = 811
  Juggle(*s, *s\chasm)
Case 811 ; FORTRAN 1602
  *s\phase = 812
  *s\phase = 291 : Continue
Case 812 ; FORTRAN 1606 label 8180
  *s\phase = 813
  If Not *s\answerReady
    *s\phase = 812
    *s\yesMessage = 54
    *s\noMessage = 54
    *s\questionMessage = 22
    Emit(*db, *out, 6, *s\questionMessage)
    *s\awaiting = 2 : *out\inputMode = #Question : ProcedureReturn
  EndIf
  *s\answerReady = 0
  *s\gaveup = *s\answer
Case 813 ; FORTRAN 1607 label 8185
  *s\phase = 814
  If *s\gaveup
    *s\phase = 1039 : Continue
  EndIf
Case 814 ; FORTRAN 1608
  *s\phase = 815
  *s\phase = 292 : Continue
Case 815 ; FORTRAN 1612 label 9190
  *s\phase = 816
  If Bool(Bool(At(*db, *s, *s\obj) Or (Bool(Bool(Liq(*db, *s, 0) = *s\obj) And At(*db, *s, *s\bottle)))) Or Bool(*s\k = Liqloc(*db, *s, *s\loc)))
    *s\spk = 94
  EndIf
Case 816 ; FORTRAN 1614
  *s\phase = 817
  *s\i = 1
Case 817 ; FORTRAN 1615 label 9192
  *s\phase = 818
  If Bool(Bool(Bool(*s\dloc[*s\i] = *s\loc) And Bool(*s\dflag >= 2)) And Bool(*s\obj = *s\dwarf))
    *s\spk = 94
  EndIf
  *s\i + 1
  If *s\i <= 5 : *s\phase = 817 : EndIf
Case 818 ; FORTRAN 1616
  *s\phase = 819
  If *s\closed
    *s\spk = 138
  EndIf
Case 819 ; FORTRAN 1617
  *s\phase = 820
  If Toting(*db, *s, *s\obj)
    *s\spk = 24
  EndIf
Case 820 ; FORTRAN 1618
  *s\phase = 821
  *s\phase = 291 : Continue
Case 821 ; FORTRAN 1622 label 8200
  *s\phase = 822
  *s\spk = 98
Case 822 ; FORTRAN 1623
  *s\phase = 823
  *s\i = 1
Case 823 ; FORTRAN 1624
  *s\phase = 824
  *s\idondx = *s\i
Case 824 ; FORTRAN 1625
  *s\phase = 825
  If Bool(Bool(*s\idondx = *s\bear) Or Bool(Not Toting(*db, *s, *s\idondx)))
    *s\phase = 830 : Continue
  EndIf
Case 825 ; FORTRAN 1626
  *s\phase = 826
  If Bool(*s\spk = 98)
    Emit(*db, *out, 6, 99)
  EndIf
Case 826 ; FORTRAN 1627
  *s\phase = 827
  *s\blklin = 0
Case 827 ; FORTRAN 1628
  *s\phase = 828
  Emit(*db, *out, 5, *s\idondx, (-1))
Case 828 ; FORTRAN 1629
  *s\phase = 829
  *s\blklin = 1
Case 829 ; FORTRAN 1630
  *s\phase = 830
  *s\spk = 0
Case 830 ; FORTRAN 1631 label 8201
  *s\phase = 831
  *s\i + 1
  If *s\i <= 100 : *s\phase = 823 : EndIf
Case 831 ; FORTRAN 1632
  *s\phase = 832
  If Toting(*db, *s, *s\bear)
    *s\spk = 141
  EndIf
Case 832 ; FORTRAN 1633
  *s\phase = 833
  *s\phase = 291 : Continue
Case 833 ; FORTRAN 1638 label 9210
  *s\phase = 834
  If Bool(*s\obj <> *s\bird)
    *s\phase = 836 : Continue
  EndIf
Case 834 ; FORTRAN 1639
  *s\phase = 835
  *s\spk = 100
Case 835 ; FORTRAN 1640
  *s\phase = 836
  *s\phase = 291 : Continue
Case 836 ; FORTRAN 1642 label 9212
  *s\phase = 837
  If Bool(Bool(Bool(*s\obj <> *s\snake) And Bool(*s\obj <> *s\dragon)) And Bool(*s\obj <> *s\troll))
    *s\phase = 846 : Continue
  EndIf
Case 837 ; FORTRAN 1643
  *s\phase = 838
  *s\spk = 102
Case 838 ; FORTRAN 1644
  *s\phase = 839
  If Bool(Bool(*s\obj = *s\dragon) And Bool(*s\prop[*s\dragon] <> 0))
    *s\spk = 110
  EndIf
Case 839 ; FORTRAN 1645
  *s\phase = 840
  If Bool(*s\obj = *s\troll)
    *s\spk = 182
  EndIf
Case 840 ; FORTRAN 1646
  *s\phase = 841
  If Bool(Bool(Bool(*s\obj <> *s\snake) Or *s\closed) Or Bool(Not Here(*db, *s, *s\bird)))
    *s\phase = 291 : Continue
  EndIf
Case 841 ; FORTRAN 1647
  *s\phase = 842
  *s\spk = 101
Case 842 ; FORTRAN 1648
  *s\phase = 843
  Dstroy(*s, *s\bird)
Case 843 ; FORTRAN 1649
  *s\phase = 844
  *s\prop[*s\bird] = 0
Case 844 ; FORTRAN 1650
  *s\phase = 845
  *s\tally2 = (*s\tally2 + 1)
Case 845 ; FORTRAN 1651
  *s\phase = 846
  *s\phase = 291 : Continue
Case 846 ; FORTRAN 1653 label 9213
  *s\phase = 847
  If Bool(*s\obj <> *s\dwarf)
    *s\phase = 851 : Continue
  EndIf
Case 847 ; FORTRAN 1654
  *s\phase = 848
  If Bool(Not Here(*db, *s, *s\food))
    *s\phase = 291 : Continue
  EndIf
Case 848 ; FORTRAN 1655
  *s\phase = 849
  *s\spk = 103
Case 849 ; FORTRAN 1656
  *s\phase = 850
  *s\dflag = (*s\dflag + 1)
Case 850 ; FORTRAN 1657
  *s\phase = 851
  *s\phase = 291 : Continue
Case 851 ; FORTRAN 1659 label 9214
  *s\phase = 852
  If Bool(*s\obj <> *s\bear)
    *s\phase = 861 : Continue
  EndIf
Case 852 ; FORTRAN 1660
  *s\phase = 853
  If Bool(*s\prop[*s\bear] = 0)
    *s\spk = 102
  EndIf
Case 853 ; FORTRAN 1661
  *s\phase = 854
  If Bool(*s\prop[*s\bear] = 3)
    *s\spk = 110
  EndIf
Case 854 ; FORTRAN 1662
  *s\phase = 855
  If Bool(Not Here(*db, *s, *s\food))
    *s\phase = 291 : Continue
  EndIf
Case 855 ; FORTRAN 1663
  *s\phase = 856
  Dstroy(*s, *s\food)
Case 856 ; FORTRAN 1664
  *s\phase = 857
  *s\prop[*s\bear] = 1
Case 857 ; FORTRAN 1665
  *s\phase = 858
  *s\fixed[*s\axe] = 0
Case 858 ; FORTRAN 1666
  *s\phase = 859
  *s\prop[*s\axe] = 0
Case 859 ; FORTRAN 1667
  *s\phase = 860
  *s\spk = 168
Case 860 ; FORTRAN 1668
  *s\phase = 861
  *s\phase = 291 : Continue
Case 861 ; FORTRAN 1670 label 9215
  *s\phase = 862
  *s\spk = 14
Case 862 ; FORTRAN 1671
  *s\phase = 863
  *s\phase = 291 : Continue
Case 863 ; FORTRAN 1675 label 9220
  *s\phase = 864
  If Bool(*s\obj = *s\vase)
    *s\phase = 875 : Continue
  EndIf
Case 864 ; FORTRAN 1676
  *s\phase = 865
  If Bool(Bool(*s\obj <> 0) And Bool(*s\obj <> *s\bottle))
    *s\phase = 291 : Continue
  EndIf
Case 865 ; FORTRAN 1677
  *s\phase = 866
  If Bool(Bool(*s\obj = 0) And Bool(Not Here(*db, *s, *s\bottle)))
    *s\phase = 518 : Continue
  EndIf
Case 866 ; FORTRAN 1678
  *s\phase = 867
  *s\spk = 107
Case 867 ; FORTRAN 1679
  *s\phase = 868
  If Bool(Liqloc(*db, *s, *s\loc) = 0)
    *s\spk = 106
  EndIf
Case 868 ; FORTRAN 1680
  *s\phase = 869
  If Bool(Liq(*db, *s, 0) <> 0)
    *s\spk = 105
  EndIf
Case 869 ; FORTRAN 1681
  *s\phase = 870
  If Bool(*s\spk <> 107)
    *s\phase = 291 : Continue
  EndIf
Case 870 ; FORTRAN 1682
  *s\phase = 871
  *s\prop[*s\bottle] = (IDiv((*db\cond[*s\loc] % 4), 2) * 2)
Case 871 ; FORTRAN 1683
  *s\phase = 872
  *s\k = Liq(*db, *s, 0)
Case 872 ; FORTRAN 1684
  *s\phase = 873
  If Toting(*db, *s, *s\bottle)
    *s\place[*s\k] = (-1)
  EndIf
Case 873 ; FORTRAN 1685
  *s\phase = 874
  If Bool(*s\k = *s\oil)
    *s\spk = 108
  EndIf
Case 874 ; FORTRAN 1686
  *s\phase = 875
  *s\phase = 291 : Continue
Case 875 ; FORTRAN 1688 label 9222
  *s\phase = 876
  *s\spk = 29
Case 876 ; FORTRAN 1689
  *s\phase = 877
  If Bool(Liqloc(*db, *s, *s\loc) = 0)
    *s\spk = 144
  EndIf
Case 877 ; FORTRAN 1690
  *s\phase = 878
  If Bool(Bool(Liqloc(*db, *s, *s\loc) = 0) Or Bool(Not Toting(*db, *s, *s\vase)))
    *s\phase = 291 : Continue
  EndIf
Case 878 ; FORTRAN 1691
  *s\phase = 879
  Emit(*db, *out, 6, 145)
Case 879 ; FORTRAN 1692
  *s\phase = 880
  *s\prop[*s\vase] = 2
Case 880 ; FORTRAN 1693
  *s\phase = 881
  *s\fixed[*s\vase] = (-1)
Case 881 ; FORTRAN 1694
  *s\phase = 882
  *s\phase = 572 : Continue
Case 882 ; FORTRAN 1698 label 9230
  *s\phase = 883
  If Bool(Bool(*s\prop[*s\rod2] < 0) Or Bool(Not *s\closed))
    *s\phase = 291 : Continue
  EndIf
Case 883 ; FORTRAN 1699
  *s\phase = 884
  *s\bonus = 133
Case 884 ; FORTRAN 1700
  *s\phase = 885
  If Bool(*s\loc = 115)
    *s\bonus = 134
  EndIf
Case 885 ; FORTRAN 1701
  *s\phase = 886
  If Here(*db, *s, *s\rod2)
    *s\bonus = 135
  EndIf
Case 886 ; FORTRAN 1702
  *s\phase = 887
  Emit(*db, *out, 6, *s\bonus)
Case 887 ; FORTRAN 1703
  *s\phase = 888
  *s\phase = 1039 : Continue
Case 888 ; FORTRAN 1707 label 8240
  *s\phase = 889
  *s\scorng = 1
Case 889 ; FORTRAN 1708
  *s\phase = 890
  *s\phase = 1039 : Continue
Case 890 ; FORTRAN 1710 label 8241
  *s\phase = 891
  *s\scorng = 0
Case 891 ; FORTRAN 1711
  *s\phase = 892
  Text(*out, "If you were to quit now, you would score " + Str(*s\score) + " out of a possible " + Str(*s\mxscor) + ".", 8243)
Case 892 ; FORTRAN 1714
  *s\phase = 893
  If Not *s\answerReady
    *s\phase = 892
    *s\yesMessage = 54
    *s\noMessage = 54
    *s\questionMessage = 143
    Emit(*db, *out, 6, *s\questionMessage)
    *s\awaiting = 2 : *out\inputMode = #Question : ProcedureReturn
  EndIf
  *s\answerReady = 0
  *s\gaveup = *s\answer
Case 893 ; FORTRAN 1715
  *s\phase = 894
  *s\phase = 813 : Continue
Case 894 ; FORTRAN 1721 label 8250
  *s\phase = 895
  *s\k = Vocab(*db, *s\wd1, 3)
Case 895 ; FORTRAN 1722
  *s\phase = 896
  *s\spk = 42
Case 896 ; FORTRAN 1723
  *s\phase = 897
  If Bool(*s\foobar = (1 - *s\k))
    *s\phase = 899 : Continue
  EndIf
Case 897 ; FORTRAN 1724
  *s\phase = 898
  If Bool(*s\foobar <> 0)
    *s\spk = 151
  EndIf
Case 898 ; FORTRAN 1725
  *s\phase = 899
  *s\phase = 291 : Continue
Case 899 ; FORTRAN 1727 label 8252
  *s\phase = 900
  *s\foobar = *s\k
Case 900 ; FORTRAN 1728
  *s\phase = 901
  If Bool(*s\k <> 4)
    *s\phase = 289 : Continue
  EndIf
Case 901 ; FORTRAN 1729
  *s\phase = 902
  *s\foobar = 0
Case 902 ; FORTRAN 1730
  *s\phase = 903
  If Bool(Bool(*s\place[*s\eggs] = *db\plac[*s\eggs]) Or (Bool(Toting(*db, *s, *s\eggs) And Bool(*s\loc = *db\plac[*s\eggs]))))
    *s\phase = 291 : Continue
  EndIf
Case 903 ; FORTRAN 1733
  *s\phase = 904
  If Bool(Bool(Bool(*s\place[*s\eggs] = 0) And Bool(*s\place[*s\troll] = 0)) And Bool(*s\prop[*s\troll] = 0))
    *s\prop[*s\troll] = 1
  EndIf
Case 904 ; FORTRAN 1735
  *s\phase = 905
  *s\k = 2
Case 905 ; FORTRAN 1736
  *s\phase = 906
  If Here(*db, *s, *s\eggs)
    *s\k = 1
  EndIf
Case 906 ; FORTRAN 1737
  *s\phase = 907
  If Bool(*s\loc = *db\plac[*s\eggs])
    *s\k = 0
  EndIf
Case 907 ; FORTRAN 1738
  *s\phase = 908
  Move(*s, *s\eggs, *db\plac[*s\eggs])
Case 908 ; FORTRAN 1739
  *s\phase = 909
  Emit(*db, *out, 5, *s\eggs, *s\k)
Case 909 ; FORTRAN 1740
  *s\phase = 910
  *s\phase = 292 : Continue
Case 910 ; FORTRAN 1744 label 8260
  *s\phase = 911
  *s\spk = 156
Case 911 ; FORTRAN 1745
  *s\phase = 912
  *s\abbnum = 10000
Case 912 ; FORTRAN 1746
  *s\phase = 913
  *s\detail = 3
Case 913 ; FORTRAN 1747
  *s\phase = 914
  *s\phase = 291 : Continue
Case 914 ; FORTRAN 1751 label 8270
  *s\phase = 915
  If Here(*db, *s, *s\magzin)
    *s\obj = *s\magzin
  EndIf
Case 915 ; FORTRAN 1752
  *s\phase = 916
  If Here(*db, *s, *s\tablet)
    *s\obj = ((*s\obj * 100) + *s\tablet)
  EndIf
Case 916 ; FORTRAN 1753
  *s\phase = 917
  If Here(*db, *s, *s\messag)
    *s\obj = ((*s\obj * 100) + *s\messag)
  EndIf
Case 917 ; FORTRAN 1754
  *s\phase = 918
  If Bool(*s\closed And Toting(*db, *s, *s\oyster))
    *s\obj = *s\oyster
  EndIf
Case 918 ; FORTRAN 1755
  *s\phase = 919
  If Bool(Bool(Bool(*s\obj > 100) Or Bool(*s\obj = 0)) Or Dark(*db, *s, 0))
    *s\phase = 518 : Continue
  EndIf
Case 919 ; FORTRAN 1757 label 9270
  *s\phase = 920
  If Dark(*db, *s, 0)
    *s\phase = 384 : Continue
  EndIf
Case 920 ; FORTRAN 1758
  *s\phase = 921
  If Bool(*s\obj = *s\magzin)
    *s\spk = 190
  EndIf
Case 921 ; FORTRAN 1759
  *s\phase = 922
  If Bool(*s\obj = *s\tablet)
    *s\spk = 196
  EndIf
Case 922 ; FORTRAN 1760
  *s\phase = 923
  If Bool(*s\obj = *s\messag)
    *s\spk = 191
  EndIf
Case 923 ; FORTRAN 1761
  *s\phase = 924
  If Bool(Bool(Bool(*s\obj = *s\oyster) And *s\hinted[2]) And Toting(*db, *s, *s\oyster))
    *s\spk = 194
  EndIf
Case 924 ; FORTRAN 1762
  *s\phase = 925
  If Bool(Bool(Bool(Bool(*s\obj <> *s\oyster) Or *s\hinted[2]) Or Bool(Not Toting(*db, *s, *s\oyster))) Or Bool(Not *s\closed))
    *s\phase = 291 : Continue
  EndIf
Case 925 ; FORTRAN 1764
  *s\phase = 926
  If Not *s\answerReady
    *s\phase = 925
    *s\yesMessage = 193
    *s\noMessage = 54
    *s\questionMessage = 192
    Emit(*db, *out, 6, *s\questionMessage)
    *s\awaiting = 2 : *out\inputMode = #Question : ProcedureReturn
  EndIf
  *s\answerReady = 0
  *s\hinted[2] = *s\answer
Case 926 ; FORTRAN 1765
  *s\phase = 927
  *s\phase = 292 : Continue
Case 927 ; FORTRAN 1769 label 9280
  *s\phase = 928
  If Bool(*s\obj = *s\mirror)
    *s\spk = 148
  EndIf
Case 928 ; FORTRAN 1770
  *s\phase = 929
  If Bool(Bool(*s\obj = *s\vase) And Bool(*s\prop[*s\vase] = 0))
    *s\phase = 932 : Continue
  EndIf
Case 929 ; FORTRAN 1771
  *s\phase = 930
  If Bool(Bool(*s\obj <> *s\mirror) Or Bool(Not *s\closed))
    *s\phase = 291 : Continue
  EndIf
Case 930 ; FORTRAN 1772
  *s\phase = 931
  Emit(*db, *out, 6, 197)
Case 931 ; FORTRAN 1773
  *s\phase = 932
  *s\phase = 1038 : Continue
Case 932 ; FORTRAN 1775 label 9282
  *s\phase = 933
  *s\spk = 198
Case 933 ; FORTRAN 1776
  *s\phase = 934
  If Toting(*db, *s, *s\vase)
    Drop(*s, *s\vase, *s\loc)
  EndIf
Case 934 ; FORTRAN 1777
  *s\phase = 935
  *s\prop[*s\vase] = 2
Case 935 ; FORTRAN 1778
  *s\phase = 936
  *s\fixed[*s\vase] = (-1)
Case 936 ; FORTRAN 1779
  *s\phase = 937
  *s\phase = 291 : Continue
Case 937 ; FORTRAN 1783 label 9290
  *s\phase = 938
  If Bool(Bool(*s\obj <> *s\dwarf) Or Bool(Not *s\closed))
    *s\phase = 291 : Continue
  EndIf
Case 938 ; FORTRAN 1784
  *s\phase = 939
  Emit(*db, *out, 6, 199)
Case 939 ; FORTRAN 1785
  *s\phase = 940
  *s\phase = 1038 : Continue
Case 940 ; FORTRAN 1791 label 8300
  *s\phase = 941
  *out\request = 1
  *s\phase = 292 : Continue
Case 941 ; FORTRAN 1792
  *s\phase = 942
  If *s\demo
    *s\phase = 291 : Continue
  EndIf
Case 942 ; FORTRAN 1793
  *s\phase = 943
Case 943 ; FORTRAN 1797
  *s\phase = 944
  If Not *s\answerReady
    *s\phase = 943
    *s\yesMessage = 54
    *s\noMessage = 54
    *s\questionMessage = 200
    Emit(*db, *out, 6, *s\questionMessage)
    *s\awaiting = 2 : *out\inputMode = #Question : ProcedureReturn
  EndIf
  *s\answerReady = 0
  If Bool(Not *s\answer)
    *s\phase = 292 : Continue
  EndIf
Case 944 ; FORTRAN 1798
  *s\phase = 945
Case 945 ; FORTRAN 1799
  *s\phase = 946
  *s\setup = (-1)
Case 946 ; FORTRAN 1800
  *s\phase = 947
Case 947 ; FORTRAN 1802 label 8305
  *s\phase = 948
  *s\yea = 0
Case 948 ; FORTRAN 1803
  *s\phase = 949
  *s\setup = 3
Case 949 ; FORTRAN 1804
  *s\phase = 950
  *s\k = *s\null
Case 950 ; FORTRAN 1805
  *s\phase = 951
  *s\phase = 388 : Continue
Case 951 ; FORTRAN 1809 label 8310
  *s\phase = 952
  Text(*out, "This desktop cave is open at all hours.", 8310)
  *s\phase = 292 : Continue
Case 952 ; FORTRAN 1810
  *s\phase = 953
Case 953 ; FORTRAN 1811
  *s\phase = 954
  *s\phase = 292 : Continue
