; Generated by tools/port_reference.py; audit against reference labels.
Case 974 ; FORTRAN 1885 label 10000
  *s\phase = 975
  *s\prop[*s\grate] = 0
Case 975 ; FORTRAN 1886
  *s\phase = 976
  *s\prop[*s\fissur] = 0
Case 976 ; FORTRAN 1887
  *s\phase = 977
  *s\i = 1
Case 977 ; FORTRAN 1888
  *s\phase = 978
  *s\dseen[*s\i] = 0
Case 978 ; FORTRAN 1889 label 10010
  *s\phase = 979
  *s\dloc[*s\i] = 0
  *s\i + 1
  If *s\i <= 6 : *s\phase = 977 : EndIf
Case 979 ; FORTRAN 1890
  *s\phase = 980
  Move(*s, *s\troll, 0)
Case 980 ; FORTRAN 1891
  *s\phase = 981
  Move(*s, (*s\troll + 100), 0)
Case 981 ; FORTRAN 1892
  *s\phase = 982
  Move(*s, *s\troll2, *db\plac[*s\troll])
Case 982 ; FORTRAN 1893
  *s\phase = 983
  Move(*s, (*s\troll2 + 100), *db\fixd[*s\troll])
Case 983 ; FORTRAN 1894
  *s\phase = 984
  Juggle(*s, *s\chasm)
Case 984 ; FORTRAN 1895
  *s\phase = 985
  If Bool(*s\prop[*s\bear] <> 3)
    Dstroy(*s, *s\bear)
  EndIf
Case 985 ; FORTRAN 1896
  *s\phase = 986
  *s\prop[*s\chain] = 0
Case 986 ; FORTRAN 1897
  *s\phase = 987
  *s\fixed[*s\chain] = 0
Case 987 ; FORTRAN 1898
  *s\phase = 988
  *s\prop[*s\axe] = 0
Case 988 ; FORTRAN 1899
  *s\phase = 989
  *s\fixed[*s\axe] = 0
Case 989 ; FORTRAN 1900
  *s\phase = 990
  Emit(*db, *out, 6, 129)
Case 990 ; FORTRAN 1901
  *s\phase = 991
  *s\clock1 = (-1)
Case 991 ; FORTRAN 1902
  *s\phase = 992
  *s\closng = 1
Case 992 ; FORTRAN 1903
  *s\phase = 993
  *s\phase = 325 : Continue
Case 993 ; FORTRAN 1917 label 11000
  *s\phase = 994
  *s\prop[*s\bottle] = Put(*db, *s, *s\bottle, 115, 1)
Case 994 ; FORTRAN 1918
  *s\phase = 995
  *s\prop[*s\plant] = Put(*db, *s, *s\plant, 115, 0)
Case 995 ; FORTRAN 1919
  *s\phase = 996
  *s\prop[*s\oyster] = Put(*db, *s, *s\oyster, 115, 0)
Case 996 ; FORTRAN 1920
  *s\phase = 997
  *s\prop[*s\lamp] = Put(*db, *s, *s\lamp, 115, 0)
Case 997 ; FORTRAN 1921
  *s\phase = 998
  *s\prop[*s\rod] = Put(*db, *s, *s\rod, 115, 0)
Case 998 ; FORTRAN 1922
  *s\phase = 999
  *s\prop[*s\dwarf] = Put(*db, *s, *s\dwarf, 115, 0)
Case 999 ; FORTRAN 1923
  *s\phase = 1000
  *s\loc = 115
Case 1000 ; FORTRAN 1924
  *s\phase = 1001
  *s\oldloc = 115
Case 1001 ; FORTRAN 1925
  *s\phase = 1002
  *s\newloc = 115
Case 1002 ; FORTRAN 1929
  *s\phase = 1003
  *s\foo = Put(*db, *s, *s\grate, 116, 0)
Case 1003 ; FORTRAN 1930
  *s\phase = 1004
  *s\prop[*s\snake] = Put(*db, *s, *s\snake, 116, 1)
Case 1004 ; FORTRAN 1931
  *s\phase = 1005
  *s\prop[*s\bird] = Put(*db, *s, *s\bird, 116, 1)
Case 1005 ; FORTRAN 1932
  *s\phase = 1006
  *s\prop[*s\cage] = Put(*db, *s, *s\cage, 116, 0)
Case 1006 ; FORTRAN 1933
  *s\phase = 1007
  *s\prop[*s\rod2] = Put(*db, *s, *s\rod2, 116, 0)
Case 1007 ; FORTRAN 1934
  *s\phase = 1008
  *s\prop[*s\pillow] = Put(*db, *s, *s\pillow, 116, 0)
Case 1008 ; FORTRAN 1936
  *s\phase = 1009
  *s\prop[*s\mirror] = Put(*db, *s, *s\mirror, 115, 0)
Case 1009 ; FORTRAN 1937
  *s\phase = 1010
  *s\fixed[*s\mirror] = 116
Case 1010 ; FORTRAN 1939
  *s\phase = 1011
  *s\i = 1
Case 1011 ; FORTRAN 1940
  *s\phase = 1012
  *s\idondx = *s\i
Case 1012 ; FORTRAN 1941 label 11010
  *s\phase = 1013
  If Toting(*db, *s, *s\idondx)
    Dstroy(*s, *s\idondx)
  EndIf
  *s\i + 1
  If *s\i <= 100 : *s\phase = 1011 : EndIf
Case 1013 ; FORTRAN 1943
  *s\phase = 1014
  Emit(*db, *out, 6, 132)
Case 1014 ; FORTRAN 1944
  *s\phase = 1015
  *s\closed = 1
Case 1015 ; FORTRAN 1945
  *s\phase = 1016
  *s\phase = 153 : Continue
Case 1016 ; FORTRAN 1954 label 12000
  *s\phase = 1017
  Emit(*db, *out, 6, 188)
Case 1017 ; FORTRAN 1955
  *s\phase = 1018
  *s\prop[*s\batter] = 1
Case 1018 ; FORTRAN 1956
  *s\phase = 1019
  If Toting(*db, *s, *s\batter)
    Drop(*s, *s\batter, *s\loc)
  EndIf
Case 1019 ; FORTRAN 1957
  *s\phase = 1020
  *s\limit = (*s\limit + 2500)
Case 1020 ; FORTRAN 1958
  *s\phase = 1021
  *s\lmwarn = 0
Case 1021 ; FORTRAN 1959
  *s\phase = 1022
  *s\phase = 325 : Continue
Case 1022 ; FORTRAN 1961 label 12200
  *s\phase = 1023
  If Bool(*s\lmwarn Or Bool(Not Here(*db, *s, *s\lamp)))
    *s\phase = 325 : Continue
  EndIf
Case 1023 ; FORTRAN 1962
  *s\phase = 1024
  *s\lmwarn = 1
Case 1024 ; FORTRAN 1963
  *s\phase = 1025
  *s\spk = 187
Case 1025 ; FORTRAN 1964
  *s\phase = 1026
  If Bool(*s\place[*s\batter] = 0)
    *s\spk = 183
  EndIf
Case 1026 ; FORTRAN 1965
  *s\phase = 1027
  If Bool(*s\prop[*s\batter] = 1)
    *s\spk = 189
  EndIf
Case 1027 ; FORTRAN 1966
  *s\phase = 1028
  Emit(*db, *out, 6, *s\spk)
Case 1028 ; FORTRAN 1967
  *s\phase = 1029
  *s\phase = 325 : Continue
Case 1029 ; FORTRAN 1969 label 12400
  *s\phase = 1030
  *s\limit = (-1)
Case 1030 ; FORTRAN 1970
  *s\phase = 1031
  *s\prop[*s\lamp] = 0
Case 1031 ; FORTRAN 1971
  *s\phase = 1032
  If Here(*db, *s, *s\lamp)
    Emit(*db, *out, 6, 184)
  EndIf
Case 1032 ; FORTRAN 1972
  *s\phase = 1033
  *s\phase = 325 : Continue
Case 1033 ; FORTRAN 1974 label 12600
  *s\phase = 1034
  Emit(*db, *out, 6, 185)
Case 1034 ; FORTRAN 1975
  *s\phase = 1035
  *s\gaveup = 1
Case 1035 ; FORTRAN 1976
  *s\phase = 1036
  *s\phase = 1039 : Continue
Case 1036 ; FORTRAN 1980 label 13000
  *s\phase = 1037
  Emit(*db, *out, 12, 1)
Case 1037 ; FORTRAN 1981
  *s\phase = 1038
  *s\phase = 1039 : Continue
Case 1038 ; FORTRAN 1985 label 19000
  *s\phase = 1039
  Emit(*db, *out, 6, 136)
