; Generated by tools/port_reference.py; audit against reference labels.
Case 1039 ; FORTRAN 2007 label 20000
  *s\phase = 1040
  *s\score = 0
Case 1040 ; FORTRAN 2008
  *s\phase = 1041
  *s\mxscor = 0
Case 1041 ; FORTRAN 2013
  *s\phase = 1042
  *s\i = 50
Case 1042 ; FORTRAN 2014
  *s\phase = 1043
  If Bool(*db\ptext[*s\i] = 0)
    *s\phase = 1049 : Continue
  EndIf
Case 1043 ; FORTRAN 2015
  *s\phase = 1044
  *s\k = 12
Case 1044 ; FORTRAN 2016
  *s\phase = 1045
  If Bool(*s\i = *s\chest)
    *s\k = 14
  EndIf
Case 1045 ; FORTRAN 2017
  *s\phase = 1046
  If Bool(*s\i > *s\chest)
    *s\k = 16
  EndIf
Case 1046 ; FORTRAN 2018
  *s\phase = 1047
  If Bool(*s\prop[*s\i] >= 0)
    *s\score = (*s\score + 2)
  EndIf
Case 1047 ; FORTRAN 2019
  *s\phase = 1048
  If Bool(Bool(*s\place[*s\i] = 3) And Bool(*s\prop[*s\i] = 0))
    *s\score = ((*s\score + *s\k) - 2)
  EndIf
Case 1048 ; FORTRAN 2020
  *s\phase = 1049
  *s\mxscor = (*s\mxscor + *s\k)
Case 1049 ; FORTRAN 2021 label 20010
  *s\phase = 1050
  *s\i + 1
  If *s\i <= 79 : *s\phase = 1042 : EndIf
Case 1050 ; FORTRAN 2030
  *s\phase = 1051
  *s\score = (*s\score + (((*s\maxdie - *s\numdie)) * 10))
Case 1051 ; FORTRAN 2031
  *s\phase = 1052
  *s\mxscor = (*s\mxscor + (*s\maxdie * 10))
Case 1052 ; FORTRAN 2032
  *s\phase = 1053
  If Bool(Not (Bool(*s\scorng Or *s\gaveup)))
    *s\score = (*s\score + 4)
  EndIf
Case 1053 ; FORTRAN 2033
  *s\phase = 1054
  *s\mxscor = (*s\mxscor + 4)
Case 1054 ; FORTRAN 2034
  *s\phase = 1055
  If Bool(*s\dflag <> 0)
    *s\score = (*s\score + 25)
  EndIf
Case 1055 ; FORTRAN 2035
  *s\phase = 1056
  *s\mxscor = (*s\mxscor + 25)
Case 1056 ; FORTRAN 2036
  *s\phase = 1057
  If *s\closng
    *s\score = (*s\score + 25)
  EndIf
Case 1057 ; FORTRAN 2037
  *s\phase = 1058
  *s\mxscor = (*s\mxscor + 25)
Case 1058 ; FORTRAN 2038
  *s\phase = 1059
  If Bool(Not *s\closed)
    *s\phase = 1063 : Continue
  EndIf
Case 1059 ; FORTRAN 2039
  *s\phase = 1060
  If Bool(*s\bonus = 0)
    *s\score = (*s\score + 10)
  EndIf
Case 1060 ; FORTRAN 2040
  *s\phase = 1061
  If Bool(*s\bonus = 135)
    *s\score = (*s\score + 25)
  EndIf
Case 1061 ; FORTRAN 2041
  *s\phase = 1062
  If Bool(*s\bonus = 134)
    *s\score = (*s\score + 30)
  EndIf
Case 1062 ; FORTRAN 2042
  *s\phase = 1063
  If Bool(*s\bonus = 133)
    *s\score = (*s\score + 45)
  EndIf
Case 1063 ; FORTRAN 2043 label 20020
  *s\phase = 1064
  *s\mxscor = (*s\mxscor + 45)
Case 1064 ; FORTRAN 2047
  *s\phase = 1065
  If Bool(*s\place[*s\magzin] = 108)
    *s\score = (*s\score + 1)
  EndIf
Case 1065 ; FORTRAN 2048
  *s\phase = 1066
  *s\mxscor = (*s\mxscor + 1)
Case 1066 ; FORTRAN 2052
  *s\phase = 1067
  *s\score = (*s\score + 2)
Case 1067 ; FORTRAN 2053
  *s\phase = 1068
  *s\mxscor = (*s\mxscor + 2)
Case 1068 ; FORTRAN 2057
  *s\phase = 1069
  *s\i = 1
Case 1069 ; FORTRAN 2058 label 20030
  *s\phase = 1070
  If *s\hinted[*s\i]
    *s\score = (*s\score - *db\hints[*s\i*5+2])
  EndIf
  *s\i + 1
  If *s\i <= *db\hntmax : *s\phase = 1069 : EndIf
Case 1070 ; FORTRAN 2062
  *s\phase = 1071
  If *s\scorng
    *s\phase = 890 : Continue
  EndIf
Case 1071 ; FORTRAN 2066
  *s\phase = 1072
  Text(*out, "You scored " + Str(*s\score) + " out of a possible " + Str(*s\mxscor) + ", using " + Str(*s\turns) + " turns.", 20100)
Case 1072 ; FORTRAN 2070
  *s\phase = 1073
  *s\i = 1
Case 1073 ; FORTRAN 2071
  *s\phase = 1074
  If Bool(*db\cval[*s\i] >= *s\score)
    *s\phase = 1077 : Continue
  EndIf
Case 1074 ; FORTRAN 2072 label 20200
  *s\phase = 1075
  *s\i + 1
  If *s\i <= (*db\classes+1) : *s\phase = 1073 : EndIf
Case 1075 ; FORTRAN 2073
  *s\phase = 1076
  Text(*out, "You just went off my scale!!", 20202)
Case 1076 ; FORTRAN 2075
  *s\phase = 1077
  *s\phase = 1085 : Continue
Case 1077 ; FORTRAN 2077 label 20210
  *s\phase = 1078
  Speak(*db, *out, *db\ctext[*s\i])
Case 1078 ; FORTRAN 2078
  *s\phase = 1079
  If Bool(*s\i = ((*db\classes+1) - 1))
    *s\phase = 1084 : Continue
  EndIf
Case 1079 ; FORTRAN 2079
  *s\phase = 1080
  *s\k = ((*db\cval[*s\i] + 1) - *s\score)
Case 1080 ; FORTRAN 2080
  *s\phase = 1081
Case 1081 ; FORTRAN 2081
  *s\phase = 1082
  If Bool(*s\k = 1)
  EndIf
Case 1082 ; FORTRAN 2082
  *s\phase = 1083
  Text(*out, "To achieve the next higher rating, you need " + Str(*s\k) + " more points.", 20212)
Case 1083 ; FORTRAN 2085
  *s\phase = 1084
  *s\phase = 1085 : Continue
Case 1084 ; FORTRAN 2087 label 20220
  *s\phase = 1085
  Text(*out, "To achieve the next higher rating would be a neat trick! Congratulations!!", 20222)
Case 1085 ; FORTRAN 2091 label 25000
  *s\phase = 1086
  *s\ended = 1 : *out\inputMode = #Ended : ProcedureReturn
