; Generated by tools/port_reference.py; audit against reference labels.
Case 954 ; FORTRAN 1820 label 40000
  *s\phase = 955
  Select ((*s\hint - 3))
    Case 1 : *s\phase = 963
    Case 2 : *s\phase = 965
    Case 3 : *s\phase = 967
    Case 4 : *s\phase = 969
    Case 5 : *s\phase = 971
    Case 6 : *s\phase = 973
  EndSelect
  Continue
Case 955 ; FORTRAN 1822
  *s\phase = 956
  *out\text + "Internal reference error " + Str(27) : *out\inputMode = #Ended : *s\ended = 1 : ProcedureReturn
Case 956 ; FORTRAN 1824 label 40010
  *s\phase = 957
  *s\hintlc[*s\hint] = 0
Case 957 ; FORTRAN 1825
  *s\phase = 958
  If Not *s\answerReady
    *s\phase = 957
    *s\yesMessage = 0
    *s\noMessage = 54
    *s\questionMessage = *db\hints[*s\hint*5+3]
    Emit(*db, *out, 6, *s\questionMessage)
    *s\awaiting = 2 : *out\inputMode = #Question : ProcedureReturn
  EndIf
  *s\answerReady = 0
  If Bool(Not *s\answer)
    *s\phase = 300 : Continue
  EndIf
Case 958 ; FORTRAN 1826
  *s\phase = 959
  Text(*out, "I am prepared to give you a hint, but it will cost you " + Str(*db\hints[*s\hint*5+2]) + " points.", 40012)
Case 959 ; FORTRAN 1829
  *s\phase = 960
  If Not *s\answerReady
    *s\phase = 959
    *s\yesMessage = *db\hints[*s\hint*5+4]
    *s\noMessage = 54
    *s\questionMessage = 175
    Emit(*db, *out, 6, *s\questionMessage)
    *s\awaiting = 2 : *out\inputMode = #Question : ProcedureReturn
  EndIf
  *s\answerReady = 0
  *s\hinted[*s\hint] = *s\answer
Case 960 ; FORTRAN 1830
  *s\phase = 961
  If Bool(*s\hinted[*s\hint] And Bool(*s\limit > 30))
    *s\limit = (*s\limit + (30 * *db\hints[*s\hint*5+2]))
  EndIf
Case 961 ; FORTRAN 1831 label 40020
  *s\phase = 962
  *s\hintlc[*s\hint] = 0
Case 962 ; FORTRAN 1832 label 40030
  *s\phase = 963
  *s\phase = 300 : Continue
Case 963 ; FORTRAN 1836 label 40400
  *s\phase = 964
  If Bool(Bool(*s\prop[*s\grate] = 0) And Bool(Not Here(*db, *s, *s\keys)))
    *s\phase = 956 : Continue
  EndIf
Case 964 ; FORTRAN 1837
  *s\phase = 965
  *s\phase = 961 : Continue
Case 965 ; FORTRAN 1839 label 40500
  *s\phase = 966
  If Bool(Bool(Here(*db, *s, *s\bird) And Toting(*db, *s, *s\rod)) And Bool(*s\obj = *s\bird))
    *s\phase = 956 : Continue
  EndIf
Case 966 ; FORTRAN 1840
  *s\phase = 967
  *s\phase = 962 : Continue
Case 967 ; FORTRAN 1842 label 40600
  *s\phase = 968
  If Bool(Here(*db, *s, *s\snake) And Bool(Not Here(*db, *s, *s\bird)))
    *s\phase = 956 : Continue
  EndIf
Case 968 ; FORTRAN 1843
  *s\phase = 969
  *s\phase = 961 : Continue
Case 969 ; FORTRAN 1845 label 40700
  *s\phase = 970
  If Bool(Bool(Bool(Bool(*s\atloc[*s\loc] = 0) And Bool(*s\atloc[*s\oldloc] = 0)) And Bool(*s\atloc[*s\oldlc2] = 0)) And Bool(*s\holdng > 1))
    *s\phase = 956 : Continue
  EndIf
Case 970 ; FORTRAN 1847
  *s\phase = 971
  *s\phase = 961 : Continue
Case 971 ; FORTRAN 1849 label 40800
  *s\phase = 972
  If Bool(Bool(*s\prop[*s\emrald] <> (-1)) And Bool(*s\prop[*s\pyram] = (-1)))
    *s\phase = 956 : Continue
  EndIf
Case 972 ; FORTRAN 1850
  *s\phase = 973
  *s\phase = 961 : Continue
Case 973 ; FORTRAN 1852 label 40900
  *s\phase = 974
  *s\phase = 956 : Continue
