; Generated by tools/port_reference.py; audit against reference labels.
Case 388 ; FORTRAN 1005 label 8
  *s\phase = 389
  *s\kk = *db\key[*s\loc]
Case 389 ; FORTRAN 1006
  *s\phase = 390
  *s\newloc = *s\loc
Case 390 ; FORTRAN 1007
  *s\phase = 391
  If Bool(*s\kk = 0)
    *out\text + "Internal reference error " + Str(26) : *out\inputMode = #Ended : *s\ended = 1 : ProcedureReturn
  EndIf
Case 391 ; FORTRAN 1008
  *s\phase = 392
  If Bool(*s\k = *s\null)
    *s\phase = 153 : Continue
  EndIf
Case 392 ; FORTRAN 1009
  *s\phase = 393
  If Bool(*s\k = *s\back)
    *s\phase = 455 : Continue
  EndIf
Case 393 ; FORTRAN 1010
  *s\phase = 394
  If Bool(*s\k = *s\look)
    *s\phase = 478 : Continue
  EndIf
Case 394 ; FORTRAN 1011
  *s\phase = 395
  If Bool(*s\k = *s\cave)
    *s\phase = 483 : Continue
  EndIf
Case 395 ; FORTRAN 1012
  *s\phase = 396
  *s\oldlc2 = *s\oldloc
Case 396 ; FORTRAN 1013
  *s\phase = 397
  *s\oldloc = *s\loc
Case 397 ; FORTRAN 1015 label 9
  *s\phase = 398
  *s\ll = Int(Abs(*db\travel[*s\kk]))
Case 398 ; FORTRAN 1016
  *s\phase = 399
  If Bool(Bool((*s\ll % 1000) = 1) Or Bool((*s\ll % 1000) = *s\k))
    *s\phase = 402 : Continue
  EndIf
Case 399 ; FORTRAN 1017
  *s\phase = 400
  If Bool(*db\travel[*s\kk] < 0)
    *s\phase = 486 : Continue
  EndIf
Case 400 ; FORTRAN 1018
  *s\phase = 401
  *s\kk = (*s\kk + 1)
Case 401 ; FORTRAN 1019
  *s\phase = 402
  *s\phase = 397 : Continue
Case 402 ; FORTRAN 1021 label 10
  *s\phase = 403
  *s\ll = IDiv(*s\ll, 1000)
Case 403 ; FORTRAN 1022 label 11
  *s\phase = 404
  *s\newloc = IDiv(*s\ll, 1000)
Case 404 ; FORTRAN 1023
  *s\phase = 405
  *s\k = (*s\newloc % 100)
Case 405 ; FORTRAN 1024
  *s\phase = 406
  If Bool(*s\newloc <= 300)
    *s\phase = 413 : Continue
  EndIf
Case 406 ; FORTRAN 1025
  *s\phase = 407
  If Bool(*s\prop[*s\k] <> (IDiv(*s\newloc, 100) - 3))
    *s\phase = 417 : Continue
  EndIf
Case 407 ; FORTRAN 1026 label 12
  *s\phase = 408
  If Bool(*db\travel[*s\kk] < 0)
    *out\text + "Internal reference error " + Str(25) : *out\inputMode = #Ended : *s\ended = 1 : ProcedureReturn
  EndIf
Case 408 ; FORTRAN 1027
  *s\phase = 409
  *s\kk = (*s\kk + 1)
Case 409 ; FORTRAN 1028
  *s\phase = 410
  *s\newloc = IDiv(Int(Abs(*db\travel[*s\kk])), 1000)
Case 410 ; FORTRAN 1029
  *s\phase = 411
  If Bool(*s\newloc = *s\ll)
    *s\phase = 407 : Continue
  EndIf
Case 411 ; FORTRAN 1030
  *s\phase = 412
  *s\ll = *s\newloc
Case 412 ; FORTRAN 1031
  *s\phase = 413
  *s\phase = 403 : Continue
Case 413 ; FORTRAN 1033 label 13
  *s\phase = 414
  If Bool(*s\newloc <= 100)
    *s\phase = 416 : Continue
  EndIf
Case 414 ; FORTRAN 1034
  *s\phase = 415
  If Bool(Toting(*db, *s, *s\k) Or (Bool(Bool(*s\newloc > 200) And At(*db, *s, *s\k))))
    *s\phase = 417 : Continue
  EndIf
Case 415 ; FORTRAN 1035
  *s\phase = 416
  *s\phase = 407 : Continue
Case 416 ; FORTRAN 1037 label 14
  *s\phase = 417
  If Bool(Bool(*s\newloc <> 0) And Bool(Not Bool(RandomRange(*s, 100) < *s\newloc)))
    *s\phase = 407 : Continue
  EndIf
Case 417 ; FORTRAN 1038 label 16
  *s\phase = 418
  *s\newloc = (*s\ll % 1000)
Case 418 ; FORTRAN 1039
  *s\phase = 419
  If Bool(*s\newloc <= 300)
    *s\phase = 153 : Continue
  EndIf
Case 419 ; FORTRAN 1040
  *s\phase = 420
  If Bool(*s\newloc <= 500)
    *s\phase = 423 : Continue
  EndIf
Case 420 ; FORTRAN 1041
  *s\phase = 421
  Emit(*db, *out, 6, (*s\newloc - 500))
Case 421 ; FORTRAN 1042
  *s\phase = 422
  *s\newloc = *s\loc
Case 422 ; FORTRAN 1043
  *s\phase = 423
  *s\phase = 153 : Continue
Case 423 ; FORTRAN 1048 label 30000
  *s\phase = 424
  *s\newloc = (*s\newloc - 300)
Case 424 ; FORTRAN 1049
  *s\phase = 425
  Select *s\newloc
    Case 1 : *s\phase = 426
    Case 2 : *s\phase = 431
    Case 3 : *s\phase = 433
  EndSelect
  Continue
Case 425 ; FORTRAN 1050
  *s\phase = 426
  *out\text + "Internal reference error " + Str(20) : *out\inputMode = #Ended : *s\ended = 1 : ProcedureReturn
Case 426 ; FORTRAN 1056 label 30100
  *s\phase = 427
  *s\newloc = ((99 + 100) - *s\loc)
Case 427 ; FORTRAN 1057
  *s\phase = 428
  If Bool(Bool(*s\holdng = 0) Or (Bool(Bool(*s\holdng = 1) And Toting(*db, *s, *s\emrald))))
    *s\phase = 153 : Continue
  EndIf
Case 428 ; FORTRAN 1058
  *s\phase = 429
  *s\newloc = *s\loc
Case 429 ; FORTRAN 1059
  *s\phase = 430
  Emit(*db, *out, 6, 117)
Case 430 ; FORTRAN 1060
  *s\phase = 431
  *s\phase = 153 : Continue
Case 431 ; FORTRAN 1066 label 30200
  *s\phase = 432
  Drop(*s, *s\emrald, *s\loc)
Case 432 ; FORTRAN 1067
  *s\phase = 433
  *s\phase = 407 : Continue
Case 433 ; FORTRAN 1075 label 30300
  *s\phase = 434
  If Bool(*s\prop[*s\troll] <> 1)
    *s\phase = 443 : Continue
  EndIf
Case 434 ; FORTRAN 1076
  *s\phase = 435
  Emit(*db, *out, 5, *s\troll, 1)
Case 435 ; FORTRAN 1077
  *s\phase = 436
  *s\prop[*s\troll] = 0
Case 436 ; FORTRAN 1078
  *s\phase = 437
  Move(*s, *s\troll2, 0)
Case 437 ; FORTRAN 1079
  *s\phase = 438
  Move(*s, (*s\troll2 + 100), 0)
Case 438 ; FORTRAN 1080
  *s\phase = 439
  Move(*s, *s\troll, *db\plac[*s\troll])
Case 439 ; FORTRAN 1081
  *s\phase = 440
  Move(*s, (*s\troll + 100), *db\fixd[*s\troll])
Case 440 ; FORTRAN 1082
  *s\phase = 441
  Juggle(*s, *s\chasm)
Case 441 ; FORTRAN 1083
  *s\phase = 442
  *s\newloc = *s\loc
Case 442 ; FORTRAN 1084
  *s\phase = 443
  *s\phase = 153 : Continue
Case 443 ; FORTRAN 1086 label 30310
  *s\phase = 444
  *s\newloc = ((*db\plac[*s\troll] + *db\fixd[*s\troll]) - *s\loc)
Case 444 ; FORTRAN 1087
  *s\phase = 445
  If Bool(*s\prop[*s\troll] = 0)
    *s\prop[*s\troll] = 1
  EndIf
Case 445 ; FORTRAN 1088
  *s\phase = 446
  If Bool(Not Toting(*db, *s, *s\bear))
    *s\phase = 153 : Continue
  EndIf
Case 446 ; FORTRAN 1089
  *s\phase = 447
  Emit(*db, *out, 6, 162)
Case 447 ; FORTRAN 1090
  *s\phase = 448
  *s\prop[*s\chasm] = 1
Case 448 ; FORTRAN 1091
  *s\phase = 449
  *s\prop[*s\troll] = 2
Case 449 ; FORTRAN 1092
  *s\phase = 450
  Drop(*s, *s\bear, *s\newloc)
Case 450 ; FORTRAN 1093
  *s\phase = 451
  *s\fixed[*s\bear] = (-1)
Case 451 ; FORTRAN 1094
  *s\phase = 452
  *s\prop[*s\bear] = 3
Case 452 ; FORTRAN 1095
  *s\phase = 453
  If Bool(*s\prop[*s\spices] < 0)
    *s\tally2 = (*s\tally2 + 1)
  EndIf
Case 453 ; FORTRAN 1096
  *s\phase = 454
  *s\oldlc2 = *s\newloc
Case 454 ; FORTRAN 1097
  *s\phase = 455
  *s\phase = 498 : Continue
Case 455 ; FORTRAN 1104 label 20
  *s\phase = 456
  *s\k = *s\oldloc
Case 456 ; FORTRAN 1105
  *s\phase = 457
  If Forced(*db, *s, *s\k)
    *s\k = *s\oldlc2
  EndIf
Case 457 ; FORTRAN 1106
  *s\phase = 458
  *s\oldlc2 = *s\oldloc
Case 458 ; FORTRAN 1107
  *s\phase = 459
  *s\oldloc = *s\loc
Case 459 ; FORTRAN 1108
  *s\phase = 460
  *s\k2 = 0
Case 460 ; FORTRAN 1109
  *s\phase = 461
  If Bool(*s\k <> *s\loc)
    *s\phase = 463 : Continue
  EndIf
Case 461 ; FORTRAN 1110
  *s\phase = 462
  Emit(*db, *out, 6, 91)
Case 462 ; FORTRAN 1111
  *s\phase = 463
  *s\phase = 153 : Continue
Case 463 ; FORTRAN 1113 label 21
  *s\phase = 464
  *s\ll = ((IDiv(Int(Abs(*db\travel[*s\kk])), 1000)) % 1000)
Case 464 ; FORTRAN 1114
  *s\phase = 465
  If Bool(*s\ll = *s\k)
    *s\phase = 475 : Continue
  EndIf
Case 465 ; FORTRAN 1115
  *s\phase = 466
  If Bool(*s\ll > 300)
    *s\phase = 468 : Continue
  EndIf
Case 466 ; FORTRAN 1116
  *s\phase = 467
  *s\j = *db\key[*s\ll]
Case 467 ; FORTRAN 1117
  *s\phase = 468
  If Bool(Forced(*db, *s, *s\ll) And Bool(((IDiv(Int(Abs(*db\travel[*s\j])), 1000)) % 1000) = *s\k))
    *s\k2 = *s\kk
  EndIf
Case 468 ; FORTRAN 1118 label 22
  *s\phase = 469
  If Bool(*db\travel[*s\kk] < 0)
    *s\phase = 471 : Continue
  EndIf
Case 469 ; FORTRAN 1119
  *s\phase = 470
  *s\kk = (*s\kk + 1)
Case 470 ; FORTRAN 1120
  *s\phase = 471
  *s\phase = 463 : Continue
Case 471 ; FORTRAN 1122 label 23
  *s\phase = 472
  *s\kk = *s\k2
Case 472 ; FORTRAN 1123
  *s\phase = 473
  If Bool(*s\kk <> 0)
    *s\phase = 475 : Continue
  EndIf
Case 473 ; FORTRAN 1124
  *s\phase = 474
  Emit(*db, *out, 6, 140)
Case 474 ; FORTRAN 1125
  *s\phase = 475
  *s\phase = 153 : Continue
Case 475 ; FORTRAN 1127 label 25
  *s\phase = 476
  *s\k = (Int(Abs(*db\travel[*s\kk])) % 1000)
Case 476 ; FORTRAN 1128
  *s\phase = 477
  *s\kk = *db\key[*s\loc]
Case 477 ; FORTRAN 1129
  *s\phase = 478
  *s\phase = 397 : Continue
Case 478 ; FORTRAN 1134 label 30
  *s\phase = 479
  If Bool(*s\detail < 3)
    Emit(*db, *out, 6, 15)
  EndIf
Case 479 ; FORTRAN 1135
  *s\phase = 480
  *s\detail = (*s\detail + 1)
Case 480 ; FORTRAN 1136
  *s\phase = 481
  *s\wzdark = 0
Case 481 ; FORTRAN 1137
  *s\phase = 482
  *s\abb[*s\loc] = 0
Case 482 ; FORTRAN 1138
  *s\phase = 483
  *s\phase = 153 : Continue
Case 483 ; FORTRAN 1142 label 40
  *s\phase = 484
  If Bool(*s\loc < 8)
    Emit(*db, *out, 6, 57)
  EndIf
Case 484 ; FORTRAN 1143
  *s\phase = 485
  If Bool(*s\loc >= 8)
    Emit(*db, *out, 6, 58)
  EndIf
Case 485 ; FORTRAN 1144
  *s\phase = 486
  *s\phase = 153 : Continue
Case 486 ; FORTRAN 1148 label 50
  *s\phase = 487
  *s\spk = 12
Case 487 ; FORTRAN 1149
  *s\phase = 488
  If Bool(Bool(*s\k >= 43) And Bool(*s\k <= 50))
    *s\spk = 9
  EndIf
Case 488 ; FORTRAN 1150
  *s\phase = 489
  If Bool(Bool(*s\k = 29) Or Bool(*s\k = 30))
    *s\spk = 9
  EndIf
Case 489 ; FORTRAN 1151
  *s\phase = 490
  If Bool(Bool(Bool(*s\k = 7) Or Bool(*s\k = 36)) Or Bool(*s\k = 37))
    *s\spk = 10
  EndIf
Case 490 ; FORTRAN 1152
  *s\phase = 491
  If Bool(Bool(*s\k = 11) Or Bool(*s\k = 19))
    *s\spk = 11
  EndIf
Case 491 ; FORTRAN 1153
  *s\phase = 492
  If Bool(Bool(*s\verb = *s\find) Or Bool(*s\verb = *s\invent))
    *s\spk = 59
  EndIf
Case 492 ; FORTRAN 1154
  *s\phase = 493
  If Bool(Bool(*s\k = 62) Or Bool(*s\k = 65))
    *s\spk = 42
  EndIf
