; Generated by tools/port_reference.py; audit against reference labels.
Case 493 ; FORTRAN 1155
  *s\phase = 494
  If Bool(*s\k = 17)
    *s\spk = 80
  EndIf
Case 494 ; FORTRAN 1156
  *s\phase = 495
  Emit(*db, *out, 6, *s\spk)
Case 495 ; FORTRAN 1157
  *s\phase = 496
  *s\phase = 153 : Continue
Case 496 ; FORTRAN 1177 label 90
  *s\phase = 497
  Emit(*db, *out, 6, 23)
Case 497 ; FORTRAN 1178
  *s\phase = 498
  *s\oldlc2 = *s\loc
Case 498 ; FORTRAN 1182 label 99
  *s\phase = 499
  If *s\closng
    *s\phase = 515 : Continue
  EndIf
Case 499 ; FORTRAN 1183
  *s\phase = 500
  If Not *s\answerReady
    *s\phase = 499
    *s\yesMessage = (82 + (*s\numdie * 2))
    *s\noMessage = 54
    *s\questionMessage = (81 + (*s\numdie * 2))
    Emit(*db, *out, 6, *s\questionMessage)
    *s\awaiting = 2 : *out\inputMode = #Question : ProcedureReturn
  EndIf
  *s\answerReady = 0
  *s\yea = *s\answer
Case 500 ; FORTRAN 1184
  *s\phase = 501
  *s\numdie = (*s\numdie + 1)
Case 501 ; FORTRAN 1185
  *s\phase = 502
  If Bool(Bool(*s\numdie = *s\maxdie) Or Bool(Not *s\yea))
    *s\phase = 1039 : Continue
  EndIf
Case 502 ; FORTRAN 1186
  *s\phase = 503
  *s\place[*s\water] = 0
Case 503 ; FORTRAN 1187
  *s\phase = 504
  *s\place[*s\oil] = 0
Case 504 ; FORTRAN 1188
  *s\phase = 505
  If Toting(*db, *s, *s\lamp)
    *s\prop[*s\lamp] = 0
  EndIf
Case 505 ; FORTRAN 1189
  *s\phase = 506
  *s\j = 1
Case 506 ; FORTRAN 1190
  *s\phase = 507
  *s\i = (101 - *s\j)
Case 507 ; FORTRAN 1191
  *s\phase = 508
  If Bool(Not Toting(*db, *s, *s\i))
    *s\phase = 511 : Continue
  EndIf
Case 508 ; FORTRAN 1192
  *s\phase = 509
  *s\k = *s\oldlc2
Case 509 ; FORTRAN 1193
  *s\phase = 510
  If Bool(*s\i = *s\lamp)
    *s\k = 1
  EndIf
Case 510 ; FORTRAN 1194
  *s\phase = 511
  Drop(*s, *s\i, *s\k)
Case 511 ; FORTRAN 1195 label 98
  *s\phase = 512
  *s\j + 1
  If *s\j <= 100 : *s\phase = 506 : EndIf
Case 512 ; FORTRAN 1196
  *s\phase = 513
  *s\loc = 3
Case 513 ; FORTRAN 1197
  *s\phase = 514
  *s\oldloc = *s\loc
Case 514 ; FORTRAN 1198
  *s\phase = 515
  *s\phase = 260 : Continue
Case 515 ; FORTRAN 1202 label 95
  *s\phase = 516
  Emit(*db, *out, 6, 131)
Case 516 ; FORTRAN 1203
  *s\phase = 517
  *s\numdie = (*s\numdie + 1)
Case 517 ; FORTRAN 1204
  *s\phase = 518
  *s\phase = 1039 : Continue
