; Generated by tools/port_reference.py; audit against reference labels.
Case 146 ; FORTRAN 620
  *s\phase = 147
Case 147 ; FORTRAN 621
  *s\phase = 148
  *s\i = RandomRange(*s, 1)
Case 148 ; FORTRAN 622
  *s\phase = 149
  If Not *s\answerReady
    *s\phase = 148
    *s\yesMessage = 1
    *s\noMessage = 0
    *s\questionMessage = 65
    Emit(*db, *out, 6, *s\questionMessage)
    *s\awaiting = 2 : *out\inputMode = #Question : ProcedureReturn
  EndIf
  *s\answerReady = 0
  *s\hinted[3] = *s\answer
Case 149 ; FORTRAN 623
  *s\phase = 150
  *s\newloc = 1
Case 150 ; FORTRAN 624
  *s\phase = 151
  *s\setup = 3
Case 151 ; FORTRAN 625
  *s\phase = 152
  *s\limit = 330
Case 152 ; FORTRAN 626
  *s\phase = 153
  If *s\hinted[3]
    *s\limit = 1000
  EndIf
Case 153 ; FORTRAN 630 label 2
  *s\phase = 154
  If Bool(Bool(Bool(*s\newloc >= 9) Or Bool(*s\newloc = 0)) Or Bool(Not *s\closng))
    *s\phase = 158 : Continue
  EndIf
Case 154 ; FORTRAN 631
  *s\phase = 155
  Emit(*db, *out, 6, 130)
Case 155 ; FORTRAN 632
  *s\phase = 156
  *s\newloc = *s\loc
Case 156 ; FORTRAN 633
  *s\phase = 157
  If Bool(Not *s\panic)
    *s\clock2 = 15
  EndIf
Case 157 ; FORTRAN 634
  *s\phase = 158
  *s\panic = 1
Case 158 ; FORTRAN 640 label 71
  *s\phase = 159
  If Bool(Bool(Bool(*s\newloc = *s\loc) Or Forced(*db, *s, *s\loc)) Or Bitset(*db, *s, *s\loc, 3))
    *s\phase = 165 : Continue
  EndIf
Case 159 ; FORTRAN 641
  *s\phase = 160
  *s\i = 1
Case 160 ; FORTRAN 642
  *s\phase = 161
  If Bool(Bool(*s\odloc[*s\i] <> *s\newloc) Or Bool(Not *s\dseen[*s\i]))
    *s\phase = 164 : Continue
  EndIf
Case 161 ; FORTRAN 643
  *s\phase = 162
  *s\newloc = *s\loc
Case 162 ; FORTRAN 644
  *s\phase = 163
  Emit(*db, *out, 6, 2)
Case 163 ; FORTRAN 645
  *s\phase = 164
  *s\phase = 165 : Continue
Case 164 ; FORTRAN 646 label 73
  *s\phase = 165
  *s\i + 1
  If *s\i <= 5 : *s\phase = 160 : EndIf
Case 165 ; FORTRAN 647 label 74
  *s\phase = 166
  *s\loc = *s\newloc
Case 166 ; FORTRAN 659
  *s\phase = 167
  If Bool(Bool(Bool(*s\loc = 0) Or Forced(*db, *s, *s\loc)) Or Bitset(*db, *s, *s\newloc, 3))
    *s\phase = 260 : Continue
  EndIf
Case 167 ; FORTRAN 660
  *s\phase = 168
  If Bool(*s\dflag <> 0)
    *s\phase = 170 : Continue
  EndIf
Case 168 ; FORTRAN 661
  *s\phase = 169
  If Bool(*s\loc >= 15)
    *s\dflag = 1
  EndIf
Case 169 ; FORTRAN 662
  *s\phase = 170
  *s\phase = 260 : Continue
Case 170 ; FORTRAN 667 label 6000
  *s\phase = 171
  If Bool(*s\dflag <> 1)
    *s\phase = 182 : Continue
  EndIf
Case 171 ; FORTRAN 668
  *s\phase = 172
  If Bool(Bool(*s\loc < 15) Or Bool(RandomRange(*s, 100) < 95))
    *s\phase = 260 : Continue
  EndIf
Case 172 ; FORTRAN 669
  *s\phase = 173
  *s\dflag = 2
Case 173 ; FORTRAN 670
  *s\phase = 174
  *s\i = 1
Case 174 ; FORTRAN 671
  *s\phase = 175
  *s\j = (1 + RandomRange(*s, 5))
Case 175 ; FORTRAN 673 label 6001
  *s\phase = 176
  If Bool(Bool(RandomRange(*s, 100) < 50) And Bool(*s\saved = (-1)))
    *s\dloc[*s\j] = 0
  EndIf
  *s\i + 1
  If *s\i <= 2 : *s\phase = 174 : EndIf
Case 176 ; FORTRAN 674
  *s\phase = 177
  *s\i = 1
Case 177 ; FORTRAN 675
  *s\phase = 178
  If Bool(*s\dloc[*s\i] = *s\loc)
    *s\dloc[*s\i] = *s\daltlc
  EndIf
Case 178 ; FORTRAN 676 label 6002
  *s\phase = 179
  *s\odloc[*s\i] = *s\dloc[*s\i]
  *s\i + 1
  If *s\i <= 5 : *s\phase = 177 : EndIf
Case 179 ; FORTRAN 677
  *s\phase = 180
  Emit(*db, *out, 6, 3)
Case 180 ; FORTRAN 678
  *s\phase = 181
  Drop(*s, *s\axe, *s\loc)
Case 181 ; FORTRAN 679
  *s\phase = 182
  *s\phase = 260 : Continue
Case 182 ; FORTRAN 686 label 6010
  *s\phase = 183
  *s\dtotal = 0
Case 183 ; FORTRAN 687
  *s\phase = 184
  *s\attack = 0
Case 184 ; FORTRAN 688
  *s\phase = 185
  *s\stick = 0
Case 185 ; FORTRAN 689
  *s\phase = 186
  *s\i = 1
Case 186 ; FORTRAN 690
  *s\phase = 187
  If Bool(*s\dloc[*s\i] = 0)
    *s\phase = 238 : Continue
  EndIf
Case 187 ; FORTRAN 691
  *s\phase = 188
  *s\j = 1
Case 188 ; FORTRAN 692
  *s\phase = 189
  *s\kk = *s\dloc[*s\i]
Case 189 ; FORTRAN 693
  *s\phase = 190
  *s\kk = *db\key[*s\kk]
Case 190 ; FORTRAN 694
  *s\phase = 191
  If Bool(*s\kk = 0)
    *s\phase = 197 : Continue
  EndIf
Case 191 ; FORTRAN 695 label 6012
  *s\phase = 192
  *s\newloc = (IDiv(Int(Abs(*db\travel[*s\kk])), 1000) % 1000)
Case 192 ; FORTRAN 696
  *s\phase = 193
  If Bool(Bool(Bool(Bool(Bool(Bool(Bool(Bool(Bool(*s\newloc > 300) Or Bool(*s\newloc < 15)) Or Bool(*s\newloc = *s\odloc[*s\i])) Or (Bool(Bool(*s\j > 1) And Bool(*s\newloc = *s\tk[(*s\j - 1)])))) Or Bool(*s\j >= 20)) Or Bool(*s\newloc = *s\dloc[*s\i])) Or Forced(*db, *s, *s\newloc)) Or (Bool(Bool(*s\i = 6) And Bitset(*db, *s, *s\newloc, 3)))) Or Bool(IDiv(Int(Abs(*db\travel[*s\kk])), 1000000) = 100))
    *s\phase = 195 : Continue
  EndIf
Case 193 ; FORTRAN 701
  *s\phase = 194
  *s\tk[*s\j] = *s\newloc
Case 194 ; FORTRAN 702
  *s\phase = 195
  *s\j = (*s\j + 1)
Case 195 ; FORTRAN 703 label 6014
  *s\phase = 196
  *s\kk = (*s\kk + 1)
Case 196 ; FORTRAN 704
  *s\phase = 197
  If Bool(*db\travel[(*s\kk - 1)] >= 0)
    *s\phase = 191 : Continue
  EndIf
Case 197 ; FORTRAN 705 label 6016
  *s\phase = 198
  *s\tk[*s\j] = *s\odloc[*s\i]
Case 198 ; FORTRAN 706
  *s\phase = 199
  If Bool(*s\j >= 2)
    *s\j = (*s\j - 1)
  EndIf
Case 199 ; FORTRAN 707
  *s\phase = 200
  *s\j = (1 + RandomRange(*s, *s\j))
Case 200 ; FORTRAN 708
  *s\phase = 201
  *s\odloc[*s\i] = *s\dloc[*s\i]
Case 201 ; FORTRAN 709
  *s\phase = 202
  *s\dloc[*s\i] = *s\tk[*s\j]
Case 202 ; FORTRAN 710
  *s\phase = 203
  *s\dseen[*s\i] = Bool((Bool(*s\dseen[*s\i] And Bool(*s\loc >= 15))) Or (Bool(Bool(*s\dloc[*s\i] = *s\loc) Or Bool(*s\odloc[*s\i] = *s\loc))))
Case 203 ; FORTRAN 712
  *s\phase = 204
  If Bool(Not *s\dseen[*s\i])
    *s\phase = 238 : Continue
  EndIf
Case 204 ; FORTRAN 713
  *s\phase = 205
  *s\dloc[*s\i] = *s\loc
Case 205 ; FORTRAN 714
  *s\phase = 206
  If Bool(*s\i <> 6)
    *s\phase = 233 : Continue
  EndIf
Case 206 ; FORTRAN 720
  *s\phase = 207
  If Bool(Bool(*s\loc = *s\chloc) Or Bool(*s\prop[*s\chest] >= 0))
    *s\phase = 238 : Continue
  EndIf
Case 207 ; FORTRAN 721
  *s\phase = 208
  *s\k = 0
Case 208 ; FORTRAN 722
  *s\phase = 209
  *s\j = 50
Case 209 ; FORTRAN 724
  *s\phase = 210
  If Bool(Bool(*s\j = *s\pyram) And (Bool(Bool(*s\loc = *db\plac[*s\pyram]) Or Bool(*s\loc = *db\plac[*s\emrald]))))
    *s\phase = 212 : Continue
  EndIf
Case 210 ; FORTRAN 726
  *s\phase = 211
  *s\idondx = *s\j
Case 211 ; FORTRAN 727
  *s\phase = 212
  If Toting(*db, *s, *s\idondx)
    *s\phase = 216 : Continue
  EndIf
Case 212 ; FORTRAN 728 label 6020
  *s\phase = 213
  If Here(*db, *s, *s\idondx)
    *s\k = 1
  EndIf
  *s\j + 1
  If *s\j <= 79 : *s\phase = 209 : EndIf
Case 213 ; FORTRAN 729
  *s\phase = 214
  If Bool(Bool(Bool(Bool(Bool(*s\tally = (*s\tally2 + 1)) And Bool(*s\k = 0)) And Bool(*s\place[*s\chest] = 0)) And Here(*db, *s, *s\lamp)) And Bool(*s\prop[*s\lamp] = 1))
    *s\phase = 229 : Continue
  EndIf
Case 214 ; FORTRAN 731
  *s\phase = 215
  If Bool(Bool(*s\odloc[6] <> *s\dloc[6]) And Bool(RandomRange(*s, 100) < 20))
    Emit(*db, *out, 6, 127)
  EndIf
Case 215 ; FORTRAN 732
  *s\phase = 216
  *s\phase = 238 : Continue
Case 216 ; FORTRAN 734 label 6022
  *s\phase = 217
  Emit(*db, *out, 6, 128)
Case 217 ; FORTRAN 736
  *s\phase = 218
  If Bool(*s\place[*s\messag] = 0)
    Move(*s, *s\chest, *s\chloc)
  EndIf
Case 218 ; FORTRAN 737
  *s\phase = 219
  Move(*s, *s\messag, *s\chloc2)
Case 219 ; FORTRAN 738
  *s\phase = 220
  *s\j = 50
Case 220 ; FORTRAN 739
  *s\phase = 221
  If Bool(Bool(*s\j = *s\pyram) And (Bool(Bool(*s\loc = *db\plac[*s\pyram]) Or Bool(*s\loc = *db\plac[*s\emrald]))))
    *s\phase = 224 : Continue
  EndIf
Case 221 ; FORTRAN 741
  *s\phase = 222
  *s\idondx = *s\j
Case 222 ; FORTRAN 742
  *s\phase = 223
  If Bool(At(*db, *s, *s\idondx) And Bool(*s\fixed[*s\idondx] = 0))
    Carry(*s, *s\idondx, *s\loc)
  EndIf
Case 223 ; FORTRAN 744
  *s\phase = 224
  If Toting(*db, *s, *s\idondx)
    Drop(*s, *s\idondx, *s\chloc)
  EndIf
Case 224 ; FORTRAN 745 label 6023
  *s\phase = 225
  *s\j + 1
  If *s\j <= 79 : *s\phase = 220 : EndIf
Case 225 ; FORTRAN 746 label 6024
  *s\phase = 226
  *s\dloc[6] = *s\chloc
Case 226 ; FORTRAN 747
  *s\phase = 227
  *s\odloc[6] = *s\chloc
Case 227 ; FORTRAN 748
  *s\phase = 228
  *s\dseen[6] = 0
Case 228 ; FORTRAN 749
  *s\phase = 229
  *s\phase = 238 : Continue
Case 229 ; FORTRAN 751 label 6025
  *s\phase = 230
  Emit(*db, *out, 6, 186)
Case 230 ; FORTRAN 752
  *s\phase = 231
  Move(*s, *s\chest, *s\chloc)
Case 231 ; FORTRAN 753
  *s\phase = 232
  Move(*s, *s\messag, *s\chloc2)
Case 232 ; FORTRAN 754
  *s\phase = 233
  *s\phase = 225 : Continue
Case 233 ; FORTRAN 758 label 6027
  *s\phase = 234
  *s\dtotal = (*s\dtotal + 1)
Case 234 ; FORTRAN 759
  *s\phase = 235
  If Bool(*s\odloc[*s\i] <> *s\dloc[*s\i])
    *s\phase = 238 : Continue
  EndIf
Case 235 ; FORTRAN 760
  *s\phase = 236
  *s\attack = (*s\attack + 1)
Case 236 ; FORTRAN 761
  *s\phase = 237
  If Bool(*s\knfloc >= 0)
    *s\knfloc = *s\loc
  EndIf
Case 237 ; FORTRAN 762
  *s\phase = 238
  If Bool(RandomRange(*s, 1000) < (95 * ((*s\dflag - 2))))
    *s\stick = (*s\stick + 1)
  EndIf
Case 238 ; FORTRAN 763 label 6030
  *s\phase = 239
  *s\i + 1
  If *s\i <= 6 : *s\phase = 186 : EndIf
Case 239 ; FORTRAN 767
  *s\phase = 240
  If Bool(*s\dtotal = 0)
    *s\phase = 260 : Continue
  EndIf
Case 240 ; FORTRAN 768
  *s\phase = 241
  If Bool(*s\dtotal = 1)
    *s\phase = 243 : Continue
  EndIf
Case 241 ; FORTRAN 769
  *s\phase = 242
  Text(*out, Str(*s\dtotal) + " threatening little dwarves are in the room with you.", 67)
Case 242 ; FORTRAN 772
  *s\phase = 243
  *s\phase = 244 : Continue
Case 243 ; FORTRAN 773 label 75
  *s\phase = 244
  Emit(*db, *out, 6, 4)
Case 244 ; FORTRAN 774 label 77
  *s\phase = 245
  If Bool(*s\attack = 0)
    *s\phase = 260 : Continue
  EndIf
Case 245 ; FORTRAN 775
  *s\phase = 246
  If Bool(*s\dflag = 2)
    *s\dflag = 3
  EndIf
Case 246 ; FORTRAN 777
  *s\phase = 247
  If Bool(*s\saved <> (-1))
    *s\dflag = 20
  EndIf
Case 247 ; FORTRAN 778
  *s\phase = 248
  If Bool(*s\attack = 1)
    *s\phase = 257 : Continue
  EndIf
Case 248 ; FORTRAN 779
  *s\phase = 249
  Text(*out, Str(*s\attack) + " of them throw knives at you!", 78)
Case 249 ; FORTRAN 781
  *s\phase = 250
  *s\k = 6
Case 250 ; FORTRAN 782 label 82
  *s\phase = 251
  If Bool(*s\stick > 1)
    *s\phase = 254 : Continue
  EndIf
Case 251 ; FORTRAN 783
  *s\phase = 252
  Emit(*db, *out, 6, (*s\k + *s\stick))
Case 252 ; FORTRAN 784
  *s\phase = 253
  If Bool(*s\stick = 0)
    *s\phase = 260 : Continue
  EndIf
Case 253 ; FORTRAN 785
  *s\phase = 254
  *s\phase = 255 : Continue
Case 254 ; FORTRAN 786 label 83
  *s\phase = 255
  Text(*out, Str(*s\stick) + " of them get you!", 68)
Case 255 ; FORTRAN 788 label 84
  *s\phase = 256
  *s\oldlc2 = *s\loc
Case 256 ; FORTRAN 789
  *s\phase = 257
  *s\phase = 498 : Continue
