; Generated by tools/port_reference.py; audit against reference labels.
Case 1 ; FORTRAN 372 label 1100
  *s\phase = 2
  If Bool(*s\setup = 2)
    *s\phase = 145 : Continue
  EndIf
Case 2 ; FORTRAN 373
  *s\phase = 3
  If Bool(*s\setup = (-1))
    *s\phase = 947 : Continue
  EndIf
Case 3 ; FORTRAN 383
  *s\phase = 4
  *s\i = 1
Case 4 ; FORTRAN 384
  *s\phase = 5
  *s\place[*s\i] = 0
Case 5 ; FORTRAN 385
  *s\phase = 6
  *s\prop[*s\i] = 0
Case 6 ; FORTRAN 386
  *s\phase = 7
  *s\link[*s\i] = 0
Case 7 ; FORTRAN 387 label 1101
  *s\phase = 8
  *s\link[(*s\i + 100)] = 0
  *s\i + 1
  If *s\i <= 100 : *s\phase = 4 : EndIf
Case 8 ; FORTRAN 389
  *s\phase = 9
  *s\i = 1
Case 9 ; FORTRAN 390
  *s\phase = 10
  *s\abb[*s\i] = 0
Case 10 ; FORTRAN 391
  *s\phase = 11
  If Bool(Bool(*db\ltext[*s\i] = 0) Or Bool(*db\key[*s\i] = 0))
    *s\phase = 13 : Continue
  EndIf
Case 11 ; FORTRAN 392
  *s\phase = 12
  *s\k = *db\key[*s\i]
Case 12 ; FORTRAN 393
  *s\phase = 13
  If Bool((Int(Abs(*db\travel[*s\k])) % 1000) = 1)
    *db\cond[*s\i] = 2
  EndIf
Case 13 ; FORTRAN 394 label 1102
  *s\phase = 14
  *s\atloc[*s\i] = 0
  *s\i + 1
  If *s\i <= 150 : *s\phase = 9 : EndIf
Case 14 ; FORTRAN 403
  *s\phase = 15
  *s\i = 1
Case 15 ; FORTRAN 404
  *s\phase = 16
  *s\k = (101 - *s\i)
Case 16 ; FORTRAN 405
  *s\phase = 17
  If Bool(*db\fixd[*s\k] <= 0)
    *s\phase = 19 : Continue
  EndIf
Case 17 ; FORTRAN 406
  *s\phase = 18
  Drop(*s, (*s\k + 100), *db\fixd[*s\k])
Case 18 ; FORTRAN 407
  *s\phase = 19
  Drop(*s, *s\k, *db\plac[*s\k])
Case 19 ; FORTRAN 408 label 1106
  *s\phase = 20
  *s\i + 1
  If *s\i <= 100 : *s\phase = 15 : EndIf
Case 20 ; FORTRAN 410
  *s\phase = 21
  *s\i = 1
Case 21 ; FORTRAN 411
  *s\phase = 22
  *s\k = (101 - *s\i)
Case 22 ; FORTRAN 412
  *s\phase = 23
  *s\fixed[*s\k] = *db\fixd[*s\k]
Case 23 ; FORTRAN 413 label 1107
  *s\phase = 24
  If Bool(Bool(*db\plac[*s\k] <> 0) And Bool(*db\fixd[*s\k] <= 0))
    Drop(*s, *s\k, *db\plac[*s\k])
  EndIf
  *s\i + 1
  If *s\i <= 100 : *s\phase = 21 : EndIf
Case 24 ; FORTRAN 421
  *s\phase = 25
Case 25 ; FORTRAN 422
  *s\phase = 26
  *s\tally = 0
Case 26 ; FORTRAN 423
  *s\phase = 27
  *s\tally2 = 0
Case 27 ; FORTRAN 424
  *s\phase = 28
  *s\i = 50
Case 28 ; FORTRAN 425
  *s\phase = 29
  If Bool(*db\ptext[*s\i] <> 0)
    *s\prop[*s\i] = (-1)
  EndIf
Case 29 ; FORTRAN 426 label 1200
  *s\phase = 30
  *s\tally = (*s\tally - *s\prop[*s\i])
  *s\i + 1
  If *s\i <= 79 : *s\phase = 28 : EndIf
Case 30 ; FORTRAN 431
  *s\phase = 31
  *s\i = 1
Case 31 ; FORTRAN 432
  *s\phase = 32
  *s\hinted[*s\i] = 0
Case 32 ; FORTRAN 433 label 1300
  *s\phase = 33
  *s\hintlc[*s\i] = 0
  *s\i + 1
  If *s\i <= *db\hntmax : *s\phase = 31 : EndIf
Case 33 ; FORTRAN 437
  *s\phase = 34
  *s\keys = Vocab(*db, ~"KEYS", 1)
Case 34 ; FORTRAN 438
  *s\phase = 35
  *s\lamp = Vocab(*db, ~"LAMP", 1)
Case 35 ; FORTRAN 439
  *s\phase = 36
  *s\grate = Vocab(*db, ~"GRATE", 1)
Case 36 ; FORTRAN 440
  *s\phase = 37
  *s\cage = Vocab(*db, ~"CAGE", 1)
Case 37 ; FORTRAN 441
  *s\phase = 38
  *s\rod = Vocab(*db, ~"ROD", 1)
Case 38 ; FORTRAN 442
  *s\phase = 39
  *s\rod2 = (*s\rod + 1)
Case 39 ; FORTRAN 443
  *s\phase = 40
  *s\steps = Vocab(*db, ~"STEPS", 1)
Case 40 ; FORTRAN 444
  *s\phase = 41
  *s\bird = Vocab(*db, ~"BIRD", 1)
Case 41 ; FORTRAN 445
  *s\phase = 42
  *s\door = Vocab(*db, ~"DOOR", 1)
Case 42 ; FORTRAN 446
  *s\phase = 43
  *s\pillow = Vocab(*db, ~"PILLO", 1)
Case 43 ; FORTRAN 447
  *s\phase = 44
  *s\snake = Vocab(*db, ~"SNAKE", 1)
Case 44 ; FORTRAN 448
  *s\phase = 45
  *s\fissur = Vocab(*db, ~"FISSU", 1)
Case 45 ; FORTRAN 449
  *s\phase = 46
  *s\tablet = Vocab(*db, ~"TABLE", 1)
Case 46 ; FORTRAN 450
  *s\phase = 47
  *s\clam = Vocab(*db, ~"CLAM", 1)
Case 47 ; FORTRAN 451
  *s\phase = 48
  *s\oyster = Vocab(*db, ~"OYSTE", 1)
Case 48 ; FORTRAN 452
  *s\phase = 49
  *s\magzin = Vocab(*db, ~"MAGAZ", 1)
Case 49 ; FORTRAN 453
  *s\phase = 50
  *s\dwarf = Vocab(*db, ~"DWARF", 1)
Case 50 ; FORTRAN 454
  *s\phase = 51
  *s\knife = Vocab(*db, ~"KNIFE", 1)
Case 51 ; FORTRAN 455
  *s\phase = 52
  *s\food = Vocab(*db, ~"FOOD", 1)
Case 52 ; FORTRAN 456
  *s\phase = 53
  *s\bottle = Vocab(*db, ~"BOTTL", 1)
Case 53 ; FORTRAN 457
  *s\phase = 54
  *s\water = Vocab(*db, ~"WATER", 1)
Case 54 ; FORTRAN 458
  *s\phase = 55
  *s\oil = Vocab(*db, ~"OIL", 1)
Case 55 ; FORTRAN 459
  *s\phase = 56
  *s\plant = Vocab(*db, ~"PLANT", 1)
Case 56 ; FORTRAN 460
  *s\phase = 57
  *s\plant2 = (*s\plant + 1)
Case 57 ; FORTRAN 461
  *s\phase = 58
  *s\axe = Vocab(*db, ~"AXE", 1)
Case 58 ; FORTRAN 462
  *s\phase = 59
  *s\mirror = Vocab(*db, ~"MIRRO", 1)
Case 59 ; FORTRAN 463
  *s\phase = 60
  *s\dragon = Vocab(*db, ~"DRAGO", 1)
Case 60 ; FORTRAN 464
  *s\phase = 61
  *s\chasm = Vocab(*db, ~"CHASM", 1)
Case 61 ; FORTRAN 465
  *s\phase = 62
  *s\troll = Vocab(*db, ~"TROLL", 1)
Case 62 ; FORTRAN 466
  *s\phase = 63
  *s\troll2 = (*s\troll + 1)
Case 63 ; FORTRAN 467
  *s\phase = 64
  *s\bear = Vocab(*db, ~"BEAR", 1)
Case 64 ; FORTRAN 468
  *s\phase = 65
  *s\messag = Vocab(*db, ~"MESSA", 1)
Case 65 ; FORTRAN 469
  *s\phase = 66
  *s\vend = Vocab(*db, ~"VENDI", 1)
Case 66 ; FORTRAN 470
  *s\phase = 67
  *s\batter = Vocab(*db, ~"BATTE", 1)
Case 67 ; FORTRAN 474
  *s\phase = 68
  *s\nugget = Vocab(*db, ~"GOLD", 1)
Case 68 ; FORTRAN 475
  *s\phase = 69
  *s\coins = Vocab(*db, ~"COINS", 1)
Case 69 ; FORTRAN 476
  *s\phase = 70
  *s\chest = Vocab(*db, ~"CHEST", 1)
Case 70 ; FORTRAN 477
  *s\phase = 71
  *s\eggs = Vocab(*db, ~"EGGS", 1)
Case 71 ; FORTRAN 478
  *s\phase = 72
  *s\tridnt = Vocab(*db, ~"TRIDE", 1)
Case 72 ; FORTRAN 479
  *s\phase = 73
  *s\vase = Vocab(*db, ~"VASE", 1)
Case 73 ; FORTRAN 480
  *s\phase = 74
  *s\emrald = Vocab(*db, ~"EMERA", 1)
Case 74 ; FORTRAN 481
  *s\phase = 75
  *s\pyram = Vocab(*db, ~"PYRAM", 1)
Case 75 ; FORTRAN 482
  *s\phase = 76
  *s\pearl = Vocab(*db, ~"PEARL", 1)
Case 76 ; FORTRAN 483
  *s\phase = 77
  *s\rug = Vocab(*db, ~"RUG", 1)
Case 77 ; FORTRAN 484
  *s\phase = 78
  *s\chain = Vocab(*db, ~"CHAIN", 1)
Case 78 ; FORTRAN 488
  *s\phase = 79
  *s\back = Vocab(*db, ~"BACK", 0)
Case 79 ; FORTRAN 489
  *s\phase = 80
  *s\look = Vocab(*db, ~"LOOK", 0)
Case 80 ; FORTRAN 490
  *s\phase = 81
  *s\cave = Vocab(*db, ~"CAVE", 0)
Case 81 ; FORTRAN 491
  *s\phase = 82
  *s\null = Vocab(*db, ~"NULL", 0)
Case 82 ; FORTRAN 492
  *s\phase = 83
  *s\entrnc = Vocab(*db, ~"ENTRA", 0)
Case 83 ; FORTRAN 493
  *s\phase = 84
  *s\dprssn = Vocab(*db, ~"DEPRE", 0)
Case 84 ; FORTRAN 497
  *s\phase = 85
  *s\say = Vocab(*db, ~"SAY", 2)
Case 85 ; FORTRAN 498
  *s\phase = 86
  *s\lock = Vocab(*db, ~"LOCK", 2)
Case 86 ; FORTRAN 499
  *s\phase = 87
  *s\throw = Vocab(*db, ~"THROW", 2)
Case 87 ; FORTRAN 500
  *s\phase = 88
  *s\find = Vocab(*db, ~"FIND", 2)
Case 88 ; FORTRAN 501
  *s\phase = 89
  *s\invent = Vocab(*db, ~"INVEN", 2)
Case 89 ; FORTRAN 517
  *s\phase = 90
  *s\chloc = 114
Case 90 ; FORTRAN 518
  *s\phase = 91
  *s\chloc2 = 140
Case 91 ; FORTRAN 519
  *s\phase = 92
  *s\i = 1
Case 92 ; FORTRAN 520 label 1700
  *s\phase = 93
  *s\dseen[*s\i] = 0
  *s\i + 1
  If *s\i <= 6 : *s\phase = 92 : EndIf
Case 93 ; FORTRAN 521
  *s\phase = 94
  *s\dflag = 0
Case 94 ; FORTRAN 522
  *s\phase = 95
  *s\dloc[1] = 19
Case 95 ; FORTRAN 523
  *s\phase = 96
  *s\dloc[2] = 27
Case 96 ; FORTRAN 524
  *s\phase = 97
  *s\dloc[3] = 33
Case 97 ; FORTRAN 525
  *s\phase = 98
  *s\dloc[4] = 44
Case 98 ; FORTRAN 526
  *s\phase = 99
  *s\dloc[5] = 64
Case 99 ; FORTRAN 527
  *s\phase = 100
  *s\dloc[6] = *s\chloc
Case 100 ; FORTRAN 528
  *s\phase = 101
  *s\daltlc = 18
Case 101 ; FORTRAN 547
  *s\phase = 102
  *s\turns = 0
Case 102 ; FORTRAN 548
  *s\phase = 103
  *s\lmwarn = 0
Case 103 ; FORTRAN 549
  *s\phase = 104
  *s\iwest = 0
Case 104 ; FORTRAN 550
  *s\phase = 105
  *s\knfloc = 0
Case 105 ; FORTRAN 551
  *s\phase = 106
  *s\detail = 0
Case 106 ; FORTRAN 552
  *s\phase = 107
  *s\abbnum = 5
Case 107 ; FORTRAN 553
  *s\phase = 108
  *s\i = 0
Case 108 ; FORTRAN 554 label 1800
  *s\phase = 109
  If Bool(*db\rtext[((2 * *s\i) + 81)] <> 0)
    *s\maxdie = (*s\i + 1)
  EndIf
  *s\i + 1
  If *s\i <= 4 : *s\phase = 108 : EndIf
Case 109 ; FORTRAN 555
  *s\phase = 110
  *s\numdie = 0
Case 110 ; FORTRAN 556
  *s\phase = 111
  *s\holdng = 0
Case 111 ; FORTRAN 557
  *s\phase = 112
  *s\dkill = 0
Case 112 ; FORTRAN 558
  *s\phase = 113
  *s\foobar = 0
Case 113 ; FORTRAN 559
  *s\phase = 114
  *s\bonus = 0
Case 114 ; FORTRAN 560
  *s\phase = 115
  *s\clock1 = 30
Case 115 ; FORTRAN 561
  *s\phase = 116
  *s\clock2 = 50
Case 116 ; FORTRAN 562
  *s\phase = 117
  *s\saved = 0
Case 117 ; FORTRAN 563
  *s\phase = 118
  *s\closng = 0
Case 118 ; FORTRAN 564
  *s\phase = 119
  *s\panic = 0
Case 119 ; FORTRAN 565
  *s\phase = 120
  *s\closed = 0
Case 120 ; FORTRAN 566
  *s\phase = 121
  *s\gaveup = 0
Case 121 ; FORTRAN 567
  *s\phase = 122
  *s\scorng = 0
Case 122 ; FORTRAN 571
  *s\phase = 123
  If Bool(*s\setup <> 1)
    *s\phase = 145 : Continue
  EndIf
Case 123 ; FORTRAN 572
  *s\phase = 124
  *s\setup = 2
Case 124 ; FORTRAN 574
  *s\phase = 125
  *s\k = 1
Case 125 ; FORTRAN 575
  *s\phase = 126
  *s\kk = ((150 + 1) - *s\k)
Case 126 ; FORTRAN 576
  *s\phase = 127
  If Bool(*db\ltext[*s\kk] <> 0)
    *s\phase = 129 : Continue
  EndIf
Case 127 ; FORTRAN 577 label 1998
  *s\phase = 128
  *s\k + 1
  If *s\k <= 150 : *s\phase = 125 : EndIf
Case 128 ; FORTRAN 579
  *s\phase = 129
  *s\obj = 0
Case 129 ; FORTRAN 580 label 1997
  *s\phase = 130
  *s\k = 1
Case 130 ; FORTRAN 581 label 1996
  *s\phase = 131
  If Bool(*db\ptext[*s\k] <> 0)
    *s\obj = (*s\obj + 1)
  EndIf
  *s\k + 1
  If *s\k <= 100 : *s\phase = 130 : EndIf
Case 131 ; FORTRAN 583
  *s\phase = 132
  *s\k = 1
Case 132 ; FORTRAN 584 label 1995
  *s\phase = 133
  If Bool(IDiv(VocabIndex(*db, *s\k), 1000) = 2)
    *s\verb = (VocabIndex(*db, *s\k) - 2000)
  EndIf
  *s\k + 1
  If *s\k <= *s\tabndx : *s\phase = 132 : EndIf
Case 133 ; FORTRAN 586
  *s\phase = 134
  *s\k = 1
Case 134 ; FORTRAN 587
  *s\phase = 135
  *s\j = ((205 + 1) - *s\k)
Case 135 ; FORTRAN 588
  *s\phase = 136
  If Bool(*db\rtext[*s\j] <> 0)
    *s\phase = 137 : Continue
  EndIf
Case 136 ; FORTRAN 589 label 1994
  *s\phase = 137
  *s\k + 1
  If *s\k <= 205 : *s\phase = 134 : EndIf
Case 137 ; FORTRAN 591 label 1993
  *s\phase = 138
  *s\k = 1
Case 138 ; FORTRAN 592
  *s\phase = 139
  *s\i = ((35 + 1) - *s\k)
Case 139 ; FORTRAN 593
  *s\phase = 140
  If Bool(*db\mtext[*s\i] <> 0)
    *s\phase = 141 : Continue
  EndIf
Case 140 ; FORTRAN 594 label 1992
  *s\phase = 141
  *s\k + 1
  If *s\k <= 35 : *s\phase = 138 : EndIf
Case 141 ; FORTRAN 596 label 1991
  *s\phase = 142
  *s\k = 100
Case 142 ; FORTRAN 597
  *s\phase = 143
Case 143 ; FORTRAN 615
  *s\phase = 144
Case 144 ; FORTRAN 616
  *s\phase = 145
Case 145 ; FORTRAN 619 label 1
  *s\phase = 146
  *s\demo = 0
  *s\saved = -1
