; Immutable source vocabulary and location constants.
If *s\keys <> initial\keys : ProcedureReturn 0 : EndIf
If *s\lamp <> initial\lamp : ProcedureReturn 0 : EndIf
If *s\grate <> initial\grate : ProcedureReturn 0 : EndIf
If *s\cage <> initial\cage : ProcedureReturn 0 : EndIf
If *s\rod <> initial\rod : ProcedureReturn 0 : EndIf
If *s\steps <> initial\steps : ProcedureReturn 0 : EndIf
If *s\bird <> initial\bird : ProcedureReturn 0 : EndIf
If *s\door <> initial\door : ProcedureReturn 0 : EndIf
If *s\pillow <> initial\pillow : ProcedureReturn 0 : EndIf
If *s\snake <> initial\snake : ProcedureReturn 0 : EndIf
If *s\fissur <> initial\fissur : ProcedureReturn 0 : EndIf
If *s\tablet <> initial\tablet : ProcedureReturn 0 : EndIf
If *s\clam <> initial\clam : ProcedureReturn 0 : EndIf
If *s\oyster <> initial\oyster : ProcedureReturn 0 : EndIf
If *s\magzin <> initial\magzin : ProcedureReturn 0 : EndIf
If *s\dwarf <> initial\dwarf : ProcedureReturn 0 : EndIf
If *s\knife <> initial\knife : ProcedureReturn 0 : EndIf
If *s\food <> initial\food : ProcedureReturn 0 : EndIf
If *s\bottle <> initial\bottle : ProcedureReturn 0 : EndIf
If *s\water <> initial\water : ProcedureReturn 0 : EndIf
If *s\oil <> initial\oil : ProcedureReturn 0 : EndIf
If *s\plant <> initial\plant : ProcedureReturn 0 : EndIf
If *s\axe <> initial\axe : ProcedureReturn 0 : EndIf
If *s\mirror <> initial\mirror : ProcedureReturn 0 : EndIf
If *s\dragon <> initial\dragon : ProcedureReturn 0 : EndIf
If *s\chasm <> initial\chasm : ProcedureReturn 0 : EndIf
If *s\troll <> initial\troll : ProcedureReturn 0 : EndIf
If *s\bear <> initial\bear : ProcedureReturn 0 : EndIf
If *s\messag <> initial\messag : ProcedureReturn 0 : EndIf
If *s\vend <> initial\vend : ProcedureReturn 0 : EndIf
If *s\batter <> initial\batter : ProcedureReturn 0 : EndIf
If *s\nugget <> initial\nugget : ProcedureReturn 0 : EndIf
If *s\coins <> initial\coins : ProcedureReturn 0 : EndIf
If *s\chest <> initial\chest : ProcedureReturn 0 : EndIf
If *s\eggs <> initial\eggs : ProcedureReturn 0 : EndIf
If *s\tridnt <> initial\tridnt : ProcedureReturn 0 : EndIf
If *s\vase <> initial\vase : ProcedureReturn 0 : EndIf
If *s\emrald <> initial\emrald : ProcedureReturn 0 : EndIf
If *s\pyram <> initial\pyram : ProcedureReturn 0 : EndIf
If *s\pearl <> initial\pearl : ProcedureReturn 0 : EndIf
If *s\rug <> initial\rug : ProcedureReturn 0 : EndIf
If *s\chain <> initial\chain : ProcedureReturn 0 : EndIf
If *s\back <> initial\back : ProcedureReturn 0 : EndIf
If *s\look <> initial\look : ProcedureReturn 0 : EndIf
If *s\cave <> initial\cave : ProcedureReturn 0 : EndIf
If *s\null <> initial\null : ProcedureReturn 0 : EndIf
If *s\entrnc <> initial\entrnc : ProcedureReturn 0 : EndIf
If *s\dprssn <> initial\dprssn : ProcedureReturn 0 : EndIf
If *s\say <> initial\say : ProcedureReturn 0 : EndIf
If *s\lock <> initial\lock : ProcedureReturn 0 : EndIf
If *s\throw <> initial\throw : ProcedureReturn 0 : EndIf
If *s\find <> initial\find : ProcedureReturn 0 : EndIf
If *s\invent <> initial\invent : ProcedureReturn 0 : EndIf
If *s\maxdie <> initial\maxdie : ProcedureReturn 0 : EndIf
If *s\chloc <> initial\chloc : ProcedureReturn 0 : EndIf
If *s\chloc2 <> initial\chloc2 : ProcedureReturn 0 : EndIf
If *s\daltlc <> initial\daltlc : ProcedureReturn 0 : EndIf
If *s\spices <> initial\spices : ProcedureReturn 0 : EndIf
If *s\rod2 <> initial\rod2 : ProcedureReturn 0 : EndIf
If *s\plant2 <> initial\plant2 : ProcedureReturn 0 : EndIf
If *s\troll2 <> initial\troll2 : ProcedureReturn 0 : EndIf
