Procedure TestPlaythroughs()
  Protected w.WorldData, s.GameState, saved.GameState, c.ParseContext, r.ActionResult, fuel.i, count.i, i.i
  Protected path.s = GetTemporaryDirectory() + "festival-route-" + Str(Random(100000000)) + ".json"
  Content_Load(@w) : World_NewGame(@w, @s)
  ReachFinale(@w, @s, @c, @r)
  Check(Save_Write(@w, @s, path, @r), "save before finale")
  Check(Save_Read(@w, @saved, path, @r), "restore before finale")
  RunCommands(@w, @s, @c, "use vent|use rainwheel|use bell", @r)
  Check(Bool(s\status = #Won And World_Treasures(@w, @s) = 0), "fresh start zero-treasure win")
  PrintN("Route budget: main story used " + Str(s\turns) + " turns; " + Str(s\fuel) + " fuel remains.")
  fuel = s\fuel
  RunCommands(@w, @s, @c, "e|take crystal|w|n|n|take living light|n|n|use seedpod|take seed|e|n|use living light on buds|take pearl|e|use manifest on drawer|take crown|s|w|w|w|w|n|e|take fork|w|s|e|e|u|u|drop crystal|drop seed|drop pearl|drop crown|drop fork", @r)
  Check(Bool(s\status = #Won And s\room = "well_house" And World_Treasures(@w, @s) = 5), "all five treasures recoverable after winning")
  Check(Bool(s\fuel = fuel), "post-win travel spends no fuel")
  Check(Save_Write(@w, @s, path, @r), "save completed game")
  Check(Save_Read(@w, @saved, path, @r), "restore completed game")
  Check(Bool(saved\status = #Won And World_Treasures(@w, @saved) = 5), "completed save retains treasures")
  World_NewGame(@w, @s) : ResetStructure(@c, ParseContext)
  RunCommands(@w, @s, @c, "n|take lantern|light lantern|d|d|w|take wedge|w|use pump", @r)
  Check(Save_Write(@w, @s, path, @r), "save during pump warning")
  RunCommands(@w, @s, @c, "look|examine pump|hint|use wedge on pump|use pump|n|use valve|e|take fork|w|s|use fork on pump|use wedge on pump", @r)
  Check(Bool(s\objectLocations("fork") = "inventory" And s\flags("wedge_installed")), "treasure brace exchanges safely")
  RunCommands(@w, @s, @c, "e|e|u|u|extinguish lantern|use oil on lantern|drop fork|light lantern|d|d|e|e|take manifest|n|use manifest on cabinet|take cup|take bell|e|examine inscription|w|s|w|w|n|use irrigation|n|e|use cup on keeper|take living light|n|use living light on buds|take pearl|e|use manifest on drawer|take crown|s|w|w|use living light on pedestal|use bell|s|s|use rainwheel|use vent|use bell", @r)
  Check(Bool(s\status = #Won And World_Treasures(@w, @s) = 3), "waterworks-first route wins after detours and pressure recovery")
  World_NewGame(@w, @s) : ResetStructure(@c, ParseContext)
  RunCommands(@w, @s, @c, "n|take lantern|d|d|w|hint", @r)
  Check(Bool(s\hintLevels("pump") = 0 And s\visited("sluice_landing") = 1), "unlit entry does not discover puzzle")
  RunCommands(@w, @s, @c, "e|light lantern|w|take wedge|w|use wedge on pump|take wedge", @r)
  Check(Bool(s\objectLocations("wedge") = "pump_room"), "cannot remove active brace without replacement")
  DeleteFile(path)
EndProcedure
